In [ ]:
import os
import csv
import pandas as pd
import time
import datetime
from datetime import date, datetime
import ukbiobank.utils.utils
from ukbiobank.utils import fieldNamesToIds
from ukbiobank.utils import loadCsv
from ukbiobank.utils import addFields

Upload UKBB file

In [27]:
csv_path = '/media/hcs-sci-psy-narun/IBu/UK_BB/ukbbdata/FULL/ukb673187.csv'
ukb = ukbiobank.ukbio(ukb_csv=csv_path)

# Get DTI IDP data

In [28]:
df_dti = ukbiobank.utils.utils.loadCsv(ukbio=ukb, fields=['eid',
25488,
25489,
25490,
25491,
25492,
25493,
25496,
25497,
25498,
25499,
25500,
25501,
25502,
25503,
25505,
25506,
25504,
25494,
25495,
25507,
25508,
25509,
25510,
25511,
25512,
25513,
25514,
25650,
25651,
25652,
25653,
25654,
25655,
25658,
25659,
25660,
25661,
25662,
25663,
25664,
25665,
25667,
25668,
25666,
25656,
25657,
25669,
25670,
25671,
25672,
25673,
25674,
25675,
25676,
25704,
25705,
25706,
25707,
25708,
25709,
25712,
25713,
25714,
25715,
25716,
25717,
25718,
25719,
25721,
25722,
25720,
25710,
25711,
25723,
25724,
25725,
25726,
25727,
25728,
25729,
25730,
25569,
25570,
25571,
25572,
25573,
25574,
25577,
25578,
25579,
25580,
25581,
25582,
25583,
25584,
25586,
25587,
25585,
25575,
25576,
25588,
25589,
25590,
25591,
25592,
25593,
25594,
25595,
25596,
25597,
25598,
25599,
25600,
25601,
25604,
25605,
25606,
25607,
25608,
25609,
25610,
25611,
25613,
25614,
25612,
25602,
25603,
25615,
25616,
25617,
25618,
25619,
25620,
25621,
25622,
25623,
25624,
25625,
25626,
25627,
25628,
25631,
25632,
25633,
25634,
25635,
25636,
25637,
25638,
25640,
25641,
25639,
25629,
25630,
25642,
25643,
25644,
25645,
25646,
25647,
25648,
25649,
25515,
25516,
25517,
25518,
25519,
25520,
25523,
25524,
25525,
25526,
25527,
25528,
25529,
25530,
25532,
25533,
25531,
25521,
25522,
25534,
25535,
25536,
25537,
25538,
25539,
25540,
25541,
25542,
25543,
25544,
25545,
25546,
25547,
25550,
25551,
25552,
25553,
25554,
25555,
25556,
25557,
25559,
25560,
25558,
25548,
25549,
25561,
25562,
25563,
25564,
25565,
25566,
25567,
25568,
25677,
25678,
25679,
25680,
25681,
25682,
25685,
25686,
25687,
25688,
25689,
25690,
25691,
25692,
25694,
25695,
25693,
25683,
25684,
25696,
25697,
25698,
25699,
25700,
25701,
25702,
25703,
25079,
25078,
25073,
25072,
25059,
25071,
25070,
25091,
25090,
25093,
25092,
25063,
25062,
25089,
25088,
25095,
25094,
25061,
25058,
25067,
25066,
25065,
25064,
25056,
25057,
25083,
25082,
25075,
25074,
25085,
25084,
25077,
25076,
25087,
25086,
25060,
25069,
25068,
25081,
25080,
25099,
25098,
25097,
25096,
25103,
25102,
25101,
25100,
25367,
25366,
25361,
25360,
25347,
25359,
25358,
25379,
25378,
25381,
25380,
25351,
25350,
25377,
25376,
25383,
25382,
25349,
25346,
25355,
25354,
25353,
25352,
25344,
25345,
25371,
25370,
25363,
25362,
25373,
25372,
25365,
25364,
25375,
25374,
25348,
25357,
25356,
25369,
25368,
25387,
25386,
25385,
25384,
25391,
25390,
25389,
25388,
25463,
25462,
25457,
25456,
25443,
25455,
25454,
25475,
25474,
25477,
25476,
25447,
25446,
25473,
25472,
25479,
25478,
25445,
25442,
25451,
25450,
25449,
25448,
25440,
25441,
25467,
25466,
25459,
25458,
25469,
25468,
25461,
25460,
25471,
25470,
25444,
25453,
25452,
25465,
25464,
25483,
25482,
25481,
25480,
25487,
25486,
25485,
25484,
25223,
25222,
25217,
25216,
25203,
25215,
25214,
25235,
25234,
25237,
25236,
25207,
25206,
25233,
25232,
25239,
25238,
25205,
25202,
25211,
25210,
25209,
25208,
25200,
25201,
25227,
25226,
25219,
25218,
25229,
25228,
25221,
25220,
25231,
25230,
25204,
25213,
25212,
25225,
25224,
25243,
25242,
25241,
25240,
25247,
25246,
25245,
25244,
25271,
25270,
25265,
25264,
25251,
25263,
25262,
25283,
25282,
25285,
25284,
25255,
25254,
25281,
25280,
25287,
25286,
25253,
25250,
25259,
25258,
25257,
25256,
25248,
25249,
25275,
25274,
25267,
25266,
25277,
25276,
25269,
25268,
25279,
25278,
25252,
25261,
25260,
25273,
25272,
25291,
25290,
25289,
25288,
25295,
25294,
25293,
25292,
25319,
25318,
25313,
25312,
25299,
25311,
25310,
25331,
25330,
25333,
25332,
25303,
25302,
25329,
25328,
25335,
25334,
25301,
25298,
25307,
25306,
25305,
25304,
25296,
25297,
25323,
25322,
25315,
25314,
25325,
25324,
25317,
25316,
25327,
25326,
25300,
25309,
25308,
25321,
25320,
25339,
25338,
25337,
25336,
25343,
25342,
25341,
25340,
25127,
25126,
25121,
25120,
25107,
25119,
25118,
25139,
25138,
25141,
25140,
25111,
25110,
25137,
25136,
25143,
25142,
25109,
25106,
25115,
25114,
25113,
25112,
25104,
25105,
25131,
25130,
25123,
25122,
25133,
25132,
25125,
25124,
25135,
25134,
25108,
25117,
25116,
25129,
25128,
25147,
25146,
25145,
25144,
25151,
25150,
25149,
25148,
25175,
25174,
25169,
25168,
25155,
25167,
25166,
25187,
25186,
25189,
25188,
25159,
25158,
25185,
25184,
25191,
25190,
25157,
25154,
25163,
25162,
25161,
25160,
25152,
25153,
25179,
25178,
25171,
25170,
25181,
25180,
25173,
25172,
25183,
25182,
25156,
25165,
25164,
25177,
25176,
25195,
25194,
25193,
25192,
25199,
25198,
25197,
25196,
25415,
25414,
25409,
25408,
25395,
25407,
25406,
25427,
25426,
25429,
25428,
25399,
25398,
25425,
25424,
25431,
25430,
25397,
25394,
25403,
25402,
25401,
25400,
25392,
25393,
25419,
25418,
25411,
25410,
25421,
25420,
25413,
25412,
25423,
25422,
25396,
25405,
25404,
25417,
25416,
25435,
25434,
25433,
25432,
25439,
25438,
25437,
25436], instance=2)

In [29]:
dti = addFields(ukbio=ukb, df=df_dti, fields=['eid',
25488,
25489,
25490,
25491,
25492,
25493,
25496,
25497,
25498,
25499,
25500,
25501,
25502,
25503,
25505,
25506,
25504,
25494,
25495,
25507,
25508,
25509,
25510,
25511,
25512,
25513,
25514,
25650,
25651,
25652,
25653,
25654,
25655,
25658,
25659,
25660,
25661,
25662,
25663,
25664,
25665,
25667,
25668,
25666,
25656,
25657,
25669,
25670,
25671,
25672,
25673,
25674,
25675,
25676,
25704,
25705,
25706,
25707,
25708,
25709,
25712,
25713,
25714,
25715,
25716,
25717,
25718,
25719,
25721,
25722,
25720,
25710,
25711,
25723,
25724,
25725,
25726,
25727,
25728,
25729,
25730,
25569,
25570,
25571,
25572,
25573,
25574,
25577,
25578,
25579,
25580,
25581,
25582,
25583,
25584,
25586,
25587,
25585,
25575,
25576,
25588,
25589,
25590,
25591,
25592,
25593,
25594,
25595,
25596,
25597,
25598,
25599,
25600,
25601,
25604,
25605,
25606,
25607,
25608,
25609,
25610,
25611,
25613,
25614,
25612,
25602,
25603,
25615,
25616,
25617,
25618,
25619,
25620,
25621,
25622,
25623,
25624,
25625,
25626,
25627,
25628,
25631,
25632,
25633,
25634,
25635,
25636,
25637,
25638,
25640,
25641,
25639,
25629,
25630,
25642,
25643,
25644,
25645,
25646,
25647,
25648,
25649,
25515,
25516,
25517,
25518,
25519,
25520,
25523,
25524,
25525,
25526,
25527,
25528,
25529,
25530,
25532,
25533,
25531,
25521,
25522,
25534,
25535,
25536,
25537,
25538,
25539,
25540,
25541,
25542,
25543,
25544,
25545,
25546,
25547,
25550,
25551,
25552,
25553,
25554,
25555,
25556,
25557,
25559,
25560,
25558,
25548,
25549,
25561,
25562,
25563,
25564,
25565,
25566,
25567,
25568,
25677,
25678,
25679,
25680,
25681,
25682,
25685,
25686,
25687,
25688,
25689,
25690,
25691,
25692,
25694,
25695,
25693,
25683,
25684,
25696,
25697,
25698,
25699,
25700,
25701,
25702,
25703,
25079,
25078,
25073,
25072,
25059,
25071,
25070,
25091,
25090,
25093,
25092,
25063,
25062,
25089,
25088,
25095,
25094,
25061,
25058,
25067,
25066,
25065,
25064,
25056,
25057,
25083,
25082,
25075,
25074,
25085,
25084,
25077,
25076,
25087,
25086,
25060,
25069,
25068,
25081,
25080,
25099,
25098,
25097,
25096,
25103,
25102,
25101,
25100,
25367,
25366,
25361,
25360,
25347,
25359,
25358,
25379,
25378,
25381,
25380,
25351,
25350,
25377,
25376,
25383,
25382,
25349,
25346,
25355,
25354,
25353,
25352,
25344,
25345,
25371,
25370,
25363,
25362,
25373,
25372,
25365,
25364,
25375,
25374,
25348,
25357,
25356,
25369,
25368,
25387,
25386,
25385,
25384,
25391,
25390,
25389,
25388,
25463,
25462,
25457,
25456,
25443,
25455,
25454,
25475,
25474,
25477,
25476,
25447,
25446,
25473,
25472,
25479,
25478,
25445,
25442,
25451,
25450,
25449,
25448,
25440,
25441,
25467,
25466,
25459,
25458,
25469,
25468,
25461,
25460,
25471,
25470,
25444,
25453,
25452,
25465,
25464,
25483,
25482,
25481,
25480,
25487,
25486,
25485,
25484,
25223,
25222,
25217,
25216,
25203,
25215,
25214,
25235,
25234,
25237,
25236,
25207,
25206,
25233,
25232,
25239,
25238,
25205,
25202,
25211,
25210,
25209,
25208,
25200,
25201,
25227,
25226,
25219,
25218,
25229,
25228,
25221,
25220,
25231,
25230,
25204,
25213,
25212,
25225,
25224,
25243,
25242,
25241,
25240,
25247,
25246,
25245,
25244,
25271,
25270,
25265,
25264,
25251,
25263,
25262,
25283,
25282,
25285,
25284,
25255,
25254,
25281,
25280,
25287,
25286,
25253,
25250,
25259,
25258,
25257,
25256,
25248,
25249,
25275,
25274,
25267,
25266,
25277,
25276,
25269,
25268,
25279,
25278,
25252,
25261,
25260,
25273,
25272,
25291,
25290,
25289,
25288,
25295,
25294,
25293,
25292,
25319,
25318,
25313,
25312,
25299,
25311,
25310,
25331,
25330,
25333,
25332,
25303,
25302,
25329,
25328,
25335,
25334,
25301,
25298,
25307,
25306,
25305,
25304,
25296,
25297,
25323,
25322,
25315,
25314,
25325,
25324,
25317,
25316,
25327,
25326,
25300,
25309,
25308,
25321,
25320,
25339,
25338,
25337,
25336,
25343,
25342,
25341,
25340,
25127,
25126,
25121,
25120,
25107,
25119,
25118,
25139,
25138,
25141,
25140,
25111,
25110,
25137,
25136,
25143,
25142,
25109,
25106,
25115,
25114,
25113,
25112,
25104,
25105,
25131,
25130,
25123,
25122,
25133,
25132,
25125,
25124,
25135,
25134,
25108,
25117,
25116,
25129,
25128,
25147,
25146,
25145,
25144,
25151,
25150,
25149,
25148,
25175,
25174,
25169,
25168,
25155,
25167,
25166,
25187,
25186,
25189,
25188,
25159,
25158,
25185,
25184,
25191,
25190,
25157,
25154,
25163,
25162,
25161,
25160,
25152,
25153,
25179,
25178,
25171,
25170,
25181,
25180,
25173,
25172,
25183,
25182,
25156,
25165,
25164,
25177,
25176,
25195,
25194,
25193,
25192,
25199,
25198,
25197,
25196,
25415,
25414,
25409,
25408,
25395,
25407,
25406,
25427,
25426,
25429,
25428,
25399,
25398,
25425,
25424,
25431,
25430,
25397,
25394,
25403,
25402,
25401,
25400,
25392,
25393,
25419,
25418,
25411,
25410,
25421,
25420,
25413,
25412,
25423,
25422,
25396,
25405,
25404,
25417,
25416,
25435,
25434,
25433,
25432,
25439,
25438,
25437,
25436], instances=2)

In [30]:
dti_names = ukbiobank.utils.utils.fieldIdsToNames(ukbio=ukb, df=df_dti)
dti_names_nona = dti_names.dropna(axis=0)
dti_names_nona

,Weighted-mean ISOVF in tract forceps minor-2.0,Mean FA in posterior corona radiata on FA skeleton (right)-2.0,Mean L2 in cerebral peduncle on FA skeleton (right)-2.0,Mean OD in medial lemniscus on FA skeleton (left)-2.0,Mean OD in posterior thalamic radiation on FA skeleton (right)-2.0,Mean L3 in sagittal stratum on FA skeleton (left)-2.0,Mean L2 in tapetum on FA skeleton (right)-2.0,Mean MO in anterior corona radiata on FA skeleton (right)-2.0,Mean ICVF in superior corona radiata on FA skeleton (left)-2.0,Mean MD in external capsule on FA skeleton (right)-2.0,...,Mean OD in posterior corona radiata on FA skeleton (right)-2.0,Mean MO in medial lemniscus on FA skeleton (right)-2.0,Mean MO in anterior limb of internal capsule on FA skeleton (right)-2.0,Mean L1 in posterior corona radiata on FA skeleton (left)-2.0,Mean L2 in cingulum cingulate gyrus on FA skeleton (left)-2.0,Mean L2 in fornix on FA skeleton-2.0,Weighted-mean MO in tract forceps major-2.0,Weighted-mean FA in tract superior thalamic radiation (left)-2.0,Mean OD in cingulum cingulate gyrus on FA skeleton (right)-2.0,eid
3,0.068111,0.477334,0.000481,0.125627,0.066177,0.000416,0.001035,0.621739,0.617446,0.000796,...,0.111943,0.715013,0.814669,0.001381,0.000545,0.001456,0.769706,0.418766,0.086191,1000046
4,0.051702,0.435871,0.000487,0.115706,0.090131,0.000440,0.000944,0.657517,0.569704,0.000781,...,0.150065,0.798243,0.784270,0.001257,0.000563,0.001135,0.704638,0.399859,0.091557,1000054
15,0.076593,0.502625,0.000440,0.092360,0.108129,0.000370,0.000661,0.665573,0.689657,0.000756,...,0.136916,0.841307,0.822738,0.001300,0.000532,0.001207,0.741666,0.450957,0.089358,1000164
19,0.090531,0.504712,0.000461,0.100833,0.071933,0.000349,0.000620,0.639023,0.651657,0.000755,...,0.150099,0.746966,0.794538,0.001288,0.000552,0.001244,0.760745,0.431859,0.082995,1000203
29,0.093905,0.475363,0.000426,0.115184,0.082482,0.000432,0.000779,0.813409,0.574715,0.000757,...,0.124888,0.788852,0.910348,0.001356,0.000556,0.001141,0.729651,0.426532,0.087613,1000304
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
502307,0.098734,0.510677,0.000463,0.106731,0.077150,0.000383,0.000874,0.689128,0.643588,0.000737,...,0.128250,0.808089,0.801451,0.001238,0.000541,0.001336,0.692121,0.406565,0.076447,6024193
502315,0.076534,0.476332,0.000446,0.107427,0.089759,0.000371,0.000767,0.621231,0.673897,0.000777,...,0.163788,0.899461,0.721785,0.001214,0.000541,0.001060,0.728367,0.410834,0.096682,6024277
502322,0.095375,0.498187,0.000427,0.111718,0.081803,0.000357,0.000706,0.757721,0.667719,0.000789,...,0.160712,0.668545,0.818691,0.001232,0.000533,0.000982,0.750838,0.425741,0.092793,6024345
502348,0.083254,0.479467,0.000455,0.132597,0.073735,0.000371,0.000571,0.631219,0.645272,0.000795,...,0.143165,0.716458,0.854729,0.001259,0.000604,0.001699,0.782669,0.418009,0.112328,6024606
502349,0.100531,0.477110,0.000447,0.114117,0.076080,0.000406,0.001057,0.631906,0.652977,0.000791,...,0.129988,0.791658,0.861836,0.001374,0.000593,0.002146,0.753405,0.444458,0.093441,6024614

Mean FA is the average FA value across all voxels in a region of interest (ROI) or a whole brain. Mean FA can be used to compare the overall degree of anisotropy between different groups or conditions.

Weighted-mean FA is a variation of mean FA that takes into account the spatial distribution of FA values within an ROI or a whole brain. Weighted-mean FA is calculated by multiplying each voxel’s FA value by its distance to the mean FA skeleton, and then dividing by the sum of all distances. The mean FA skeleton is a representation of the centers of all tracts common to a group of subjects, obtained by using tract-based spatial statistics (TBSS) Weighted-mean FA gives more weight to voxels that are closer to the mean FA skeleton, and less weight to voxels that are farther away. Weighted-mean FA can be used to reduce the influence of partial volume effects and inter-subject variability on mean FA estimates.

The difference between weighted-mean FA and mean FA is that weighted-mean FA is more sensitive to changes in FA that occur near the core of white matter tracts, while mean FA is more influenced by changes in FA that occur at the boundaries of white matter tracts or in regions with multiple fiber orientations. Depending on the research question and the type of diffusion data, weighted-mean FA or mean FA may be more appropriate to use as a summary measure of anisotropy.

In [ ]:
# Remove Intance code and export to csv
dti_names_nona.columns = dti_names_nona.columns.str.replace("-2.0", "")
dti_names_nona.to_csv('/IBu/UK_BB/CSV_brain/dti_names_nona_names.csv', index=False)
dti_names.to_csv('/IBu/UK_BB/CSV_brain/dti_full_names.csv')
dti.to_csv('/IBu/UK_BB/CSV_brain/dti_full_fieldid.csv')
dti_names_nona

,Weighted-mean ISOVF in tract forceps minor,Mean FA in posterior corona radiata on FA skeleton (right),Mean L2 in cerebral peduncle on FA skeleton (right),Mean OD in medial lemniscus on FA skeleton (left),Mean OD in posterior thalamic radiation on FA skeleton (right),Mean L3 in sagittal stratum on FA skeleton (left),Mean L2 in tapetum on FA skeleton (right),Mean MO in anterior corona radiata on FA skeleton (right),Mean ICVF in superior corona radiata on FA skeleton (left),Mean MD in external capsule on FA skeleton (right),...,Mean OD in posterior corona radiata on FA skeleton (right),Mean MO in medial lemniscus on FA skeleton (right),Mean MO in anterior limb of internal capsule on FA skeleton (right),Mean L1 in posterior corona radiata on FA skeleton (left),Mean L2 in cingulum cingulate gyrus on FA skeleton (left),Mean L2 in fornix on FA skeleton,Weighted-mean MO in tract forceps major,Weighted-mean FA in tract superior thalamic radiation (left),Mean OD in cingulum cingulate gyrus on FA skeleton (right),eid
3,0.068111,0.477334,0.000481,0.125627,0.066177,0.000416,0.001035,0.621739,0.617446,0.000796,...,0.111943,0.715013,0.814669,0.001381,0.000545,0.001456,0.769706,0.418766,0.086191,1000046
4,0.051702,0.435871,0.000487,0.115706,0.090131,0.000440,0.000944,0.657517,0.569704,0.000781,...,0.150065,0.798243,0.784270,0.001257,0.000563,0.001135,0.704638,0.399859,0.091557,1000054
15,0.076593,0.502625,0.000440,0.092360,0.108129,0.000370,0.000661,0.665573,0.689657,0.000756,...,0.136916,0.841307,0.822738,0.001300,0.000532,0.001207,0.741666,0.450957,0.089358,1000164
19,0.090531,0.504712,0.000461,0.100833,0.071933,0.000349,0.000620,0.639023,0.651657,0.000755,...,0.150099,0.746966,0.794538,0.001288,0.000552,0.001244,0.760745,0.431859,0.082995,1000203
29,0.093905,0.475363,0.000426,0.115184,0.082482,0.000432,0.000779,0.813409,0.574715,0.000757,...,0.124888,0.788852,0.910348,0.001356,0.000556,0.001141,0.729651,0.426532,0.087613,1000304
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
502307,0.098734,0.510677,0.000463,0.106731,0.077150,0.000383,0.000874,0.689128,0.643588,0.000737,...,0.128250,0.808089,0.801451,0.001238,0.000541,0.001336,0.692121,0.406565,0.076447,6024193
502315,0.076534,0.476332,0.000446,0.107427,0.089759,0.000371,0.000767,0.621231,0.673897,0.000777,...,0.163788,0.899461,0.721785,0.001214,0.000541,0.001060,0.728367,0.410834,0.096682,6024277
502322,0.095375,0.498187,0.000427,0.111718,0.081803,0.000357,0.000706,0.757721,0.667719,0.000789,...,0.160712,0.668545,0.818691,0.001232,0.000533,0.000982,0.750838,0.425741,0.092793,6024345
502348,0.083254,0.479467,0.000455,0.132597,0.073735,0.000371,0.000571,0.631219,0.645272,0.000795,...,0.143165,0.716458,0.854729,0.001259,0.000604,0.001699,0.782669,0.418009,0.112328,6024606
502349,0.100531,0.477110,0.000447,0.114117,0.076080,0.000406,0.001057,0.631906,0.652977,0.000791,...,0.129988,0.791658,0.861836,0.001374,0.000593,0.002146,0.753405,0.444458,0.093441,6024614

- **Diffusion tensor** - a description of how water diffusion is altered by the presence of tissue membranes. For example, water
movement is strongly restricted perpendicular to white matter fibres but weakly along them, resulting in a elliptical diffusion
tensor. See also: MD, FA, MO, L1,2,3 [Pierpaoli and Basser, 1996, Smith et al., 2015].

- **MD** - mean diffusivity - the average strength of water diffusion, independent of direction.
- **MO** - diffusion tensor mode - a discriminant between (e.g.) the presence of a single strong fibre in a voxel, vs multiple distinct
fibres with different directions.
- **L1,2,3** - in a diffusion tensor fit, the strength of diffusion along the principal axes of the ellipse (eigenvalues).
- **ICVF** intra-cellular volume fraction - an index of white matter neurite density from NODDI modelling of dMRI data (Neurite Orien-
tation Dispersion and Density Imaging [Zhang et al., 2012, Daducci et al., 2015]). Other NODDI modelling outputs include ISOVF
(isotropic or free water volume fraction) and OD (orientation dispersion index, a measure of within-voxel tract disorganisation).

# DTI Confounds

[Forum](https://www.jiscmail.ac.uk/cgi-bin/webadmin?A0=UKB-NEUROIMAGING)

## List of confounds

- Head size: 25000
- Site: 54

*Other*
- Discrepancy between dMRI brain image and T1 brain image: 25737
- dMRIScaling: 25928 (Intensity scaling for dMRI)
- Acquisition date: 53

*Table position*
- X-position of centre-of-gravity of brain mask in scanner co-ordinates: 25756
- Z-position of centre-of-gravity of brain mask in scanner co-ordinates: 25758
- Y-position of back of brain mask in scanner co-ordinates: 25757
- Scanner table position: 25759 (Z-co-ordinate of the coil (and the scanner table that the coil sits on) within the scanner. The Z axis points down the centre of the magnet) / -999999 represents "Measure not cleanly recoverable from data"

*Head Motion*
- 90th percentile of relative head motion from dMRI: 24455
- 90th percentile of absolute head motion from dMRI: 24452
- Mean absolute head motion from dMRI: 24450
- Mean relative head motion from dMRI: 24453
- Median absolute head motion from dMRI: 24451
- Median relative head motion from dMRI: 24454
- STRUCT MOTION: 24419

*Eddy*
- Number of slices that Eddy estimated to be outliers in dMRI data: 24456
- Number of dMRI outlier slices detected and corrected: 25746
- New Eddy: 25921 (Whether increased search space in eddy current estimation was used for dMRI)
- YTranslation: 25922 (Standard deviation of apparent translation in the Y axis as measured by eddy)
- Discrepancy between T1 brain image and standard-space brain template (linearly-aligned): 25731
- Discrepancy between T1 brain image and standard-space brain template (nonlinearly-aligned): 25732
- Mean rfMRI head motion, averaged across space and time points: 25741
- Mean tfMRI head motion, averaged across space and time points: 25742

The following variables were not found:
[24455, 24452, 24453, 24450, 24451, 24454, 24419, 24456]

- 90th percentile of relative head motion from dMRI: 24455
- 90th percentile of absolute head motion from dMRI: 24452
- Mean relative head motion from dMRI: 24453
- Mean absolute head motion from dMRI: 24450
- Median absolute head motion from dMRI: 24451
- Median relative head motion from dMRI: 24454
- STRUCT MOTION: 24419
- Number of slices that Eddy estimated to be outliers in dMRI data: 24456

'SIMPLE' set of confounds (without sociodemographics):
- Head size (1 per site)
- Site (2 variables)
- Head motion (mean relative motion as calculated by FEAT) in resting fMRI (1 per site) +?
- Head motion (mean relative motion as calculated by FEAT) in task fMRI (1 per site) +?
- Date (number of days when the acquisition happened since the acquisitions started) (1 per site) ?
- Date squared (1 per site) ?

Non-linear confounds

"Non-linear transformations of age (2.25%), table position (4.44%), or head motion (3.3%). It is also interesting to note that T1w, dMRI and rfMRI Amplitude IDPs were more strongly affected in general by non-linear transformations, compared with other classes of IDPs"

Brain position measures and their squared values, head motion measures and their squared values, volumetric scaling, and estimated total intracranial volume, total brain volume (for traits other than total brain volume itself)

### Get the main set of confounds from the 'big' csv

In [32]:
df_dti_conf = ukbiobank.utils.utils.loadCsv(ukbio=ukb, fields=['eid',
25731,
25732,
25741,
25742,
25000,
54,
25737,
25928,
53,
25756,
25758,
25757,
25759,
25746,
25921,
25922,
25731,
20218,
25780], instance=2)
#24455, 24452,24453,24450,24451,24454,24419,24456 not found

/home/irinabu/anaconda3/envs/ukbiobank_py11/lib/python3.11/site-packages/ukbiobank/utils/utils.py:296: DtypeWarning: Columns (98,99,100,12985,12986) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(ukbio.csv_path, usecols=new_fields)

In [33]:
dti_conf = addFields(ukbio=ukb, df=df_dti_conf, fields=['eid',
25731,
25732,
25741,
25742,
25000,
54,
25737,
25928,
53,
25756,
25758,
25757,
25759,
25746,
25921,
25922,
25731,
20218,
25780], instances=2)

/home/irinabu/anaconda3/envs/ukbiobank_py11/lib/python3.11/site-packages/ukbiobank/utils/utils.py:296: DtypeWarning: Columns (98,99,100,12985,12986) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(ukbio.csv_path, usecols=new_fields)

In [ ]:
dti_conf_names = ukbiobank.utils.utils.fieldIdsToNames(ukbio=ukb, df=df_dti_conf)
dti_conf_names.to_csv('/IBu/UK_BB/CSV_brain/dti_conf_main_names.csv', index=False)
dti_conf_names
dti_conf_names = dti_conf_names.drop(columns = ['Acquisition protocol phase.-2.0', 'Multiband diffusion brain images - DICOM-2.0'])
dti_conf_names

,Discrepancy between T1 brain image and standard-space brain template (linearly-aligned)-2.0,Scanner transverse (Y) brain position-2.0,Intensity scaling for dMRI-2.0,Discrepancy between T1 brain image and standard-space brain template (nonlinearly-aligned)-2.0,Scanner lateral (X) brain position-2.0,Scanner table position-2.0,Date of attending assessment centre-2.0,"Mean tfMRI head motion, averaged across space and time points-2.0",Number of dMRI outlier slices detected and corrected-2.0,Increased search space in eddy current estimation used for dMRI-2.0,Discrepancy between dMRI brain image and T1 brain image-2.0,Scanner longitudinal (Z) brain position-2.0,Standard deviation of apparent translation in the Y axis as measured by eddy-2.0,Volumetric scaling from T1 head image to standard space-2.0,UK Biobank assessment centre-2.0,"Mean rfMRI head motion, averaged across space and time points-2.0",eid
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1000019
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1000022
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1000035
3,0.695184,62.0,1.0,0.487557,0.985166,-1089.0,2015-07-24,0.238552,44.0,0.0,0.624899,26.9998,1.282250,1.25540,11025.0,0.137711,1000046
4,0.657209,61.0,2.0,0.484748,-1.590050,-1042.0,2019-11-19,0.150712,96.0,1.0,0.588448,-37.5785,0.760415,1.43688,11025.0,0.169216,1000054
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
502362,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6024740
502363,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6024757
502364,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6024762
502365,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6024779
502366,NaN,NaN,NaN,NaN,NaN,NaN,2022-12-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11025.0,NaN,6024785

### Manually upload confounds that could not be uploaded from the big csv file with UKBB utils

- STRUCT MOTION: 24419
- Mean absolute head motion from dMRI: 24450
- Median absolute head motion from dMRI: 24451
- 90th percentile of absolute head motion from dMRI: 24452
- Mean relative head motion from dMRI: 24453
- Median relative head motion from dMRI: 24454
- 90th percentile of relative head motion from dMRI: 24455
- Number of slices that Eddy estimated to be outliers in dMRI data: 24456

In [ ]:
dti_conf_add_selected = pd.read_csv('/media/hcs-sci-psy-narun/IBu/UK_BB/ukbbdata/FULL/ukb673187.csv', usecols=['eid', '24419-2.0', '24450-2.0', '24451-2.0', '24452-2.0', '24453-2.0', '24454-2.0', '24455-2.0', '24456-2.0'])
dti_conf_add_selected_fullnames = dti_conf_add_selected.copy()
dti_conf_add_selected_fullnames.columns = ['eid','Struct. motion', 'Mean absolute head motion from dMRI',
                                           'Median absolute head motion from dMRI', '90th percentile of absolute head motion from dMRI',
                                           'Mean relative head motion from dMRI', 'Median relative head motion from dMRI',
                                           '90th percentile of relative head motion from dMRI', 'Number of slices that Eddy estimated to be outliers in dMRI data']
dti_conf_add_selected_fullnames.to_csv('/IBu/UK_BB/CSV_brain/dti_conf_remaining_selected_fullnames.csv')
dti_conf_add_selected_fullnames

,eid,Struct. motion,Mean absolute head motion from dMRI,Median absolute head motion from dMRI,90th percentile of absolute head motion from dMRI,Mean relative head motion from dMRI,Median relative head motion from dMRI,90th percentile of relative head motion from dMRI,Number of slices that Eddy estimated to be outliers in dMRI data
0,1000019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1000022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1000035,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1000046,0.166306,1.23674,1.06212,2.07692,1.51321,1.196260,3.01677,44.0
4,1000054,0.488937,2.61602,2.53827,3.57881,1.01966,0.996388,1.73187,96.0
...,...,...,...,...,...,...,...,...,...
502362,6024740,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
502363,6024757,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
502364,6024762,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
502365,6024779,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
502366,6024785,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [66]:
# Merge all confounds
dti_confounds_full = dti_conf_names.merge(dti_conf_add_selected_fullnames, how='inner', on='eid').reset_index(drop=True)
dti_confounds_full.isna().sum().sort_values()

eid                                                                                                    0
Date of attending assessment centre-2.0                                                           436712
UK Biobank assessment centre-2.0                                                                  436934
Struct. motion                                                                                    452946
Scanner table position-2.0                                                                        454892
Number of slices that Eddy estimated to be outliers in dMRI data                                  454986
Median relative head motion from dMRI                                                             454986
Mean relative head motion from dMRI                                                               454986
90th percentile of absolute head motion from dMRI                                                 454986
Median absolute head motion from dMRI                                                             454986
Mean absolute head motion from dMRI                                                               454986
90th percentile of relative head motion from dMRI                                                 454986
Scanner transverse (Y) brain position-2.0                                                         454987
Scanner lateral (X) brain position-2.0                                                            454987
Scanner longitudinal (Z) brain position-2.0                                                       455007
Discrepancy between T1 brain image and standard-space brain template (linearly-aligned)-2.0       455969
Volumetric scaling from T1 head image to standard space-2.0                                       455969
Discrepancy between T1 brain image and standard-space brain template (nonlinearly-aligned)-2.0    455969
Increased search space in eddy current estimation used for dMRI-2.0                               455987
Intensity scaling for dMRI-2.0                                                                    457434
Standard deviation of apparent translation in the Y axis as measured by eddy-2.0                  457738
Discrepancy between dMRI brain image and T1 brain image-2.0                                       457749
Mean rfMRI head motion, averaged across space and time points-2.0                                 457847
Number of dMRI outlier slices detected and corrected-2.0                                          458276
Mean tfMRI head motion, averaged across space and time points-2.0                                 463716
dtype: int64

In [68]:
# Remove unnecessary columns and drop NAs
dti_confounds_full.columns = dti_confounds_full.columns.str.replace("-2.0", "")
dti_confounds_full = dti_confounds_full.drop(columns=['Mean tfMRI head motion, averaged across space and time points', 'Mean rfMRI head motion, averaged across space and time points'])
dti_confounds_nona = dti_confounds_full.dropna(axis=0).reset_index(drop=True)
dti_confounds_nona

,Discrepancy between T1 brain image and standard-space brain template (linearly-aligned),Scanner transverse (Y) brain position,Intensity scaling for dMRI,Discrepancy between T1 brain image and standard-space brain template (nonlinearly-aligned),Scanner lateral (X) brain position,Scanner table position,Date of attending assessment centre,Number of dMRI outlier slices detected and corrected,Increased search space in eddy current estimation used for dMRI,Discrepancy between dMRI brain image and T1 brain image,...,UK Biobank assessment centre,eid,Struct. motion,Mean absolute head motion from dMRI,Median absolute head motion from dMRI,90th percentile of absolute head motion from dMRI,Mean relative head motion from dMRI,Median relative head motion from dMRI,90th percentile of relative head motion from dMRI,Number of slices that Eddy estimated to be outliers in dMRI data
0,0.695184,62.0,1.0,0.487557,0.985166,-1089.0,2015-07-24,44.0,0.0,0.624899,...,11025.0,1000046,0.166306,1.236740,1.062120,2.07692,1.513210,1.196260,3.01677,44.0
1,0.657209,61.0,2.0,0.484748,-1.590050,-1042.0,2019-11-19,96.0,1.0,0.588448,...,11025.0,1000054,0.488937,2.616020,2.538270,3.57881,1.019660,0.996388,1.73187,96.0
2,0.610478,63.0,2.0,0.466349,0.193689,-1042.0,2018-10-14,20.0,1.0,0.504682,...,11025.0,1000164,0.321029,2.351880,1.972630,4.14946,2.376710,1.822410,4.85173,20.0
3,0.598807,56.0,2.0,0.488218,2.003760,-1042.0,2017-11-15,44.0,0.0,0.700597,...,11025.0,1000203,0.299027,0.952011,0.678971,2.18138,1.341220,1.127860,2.45659,44.0
4,0.638328,65.0,2.0,0.543879,1.693270,-1042.0,2017-12-17,29.0,0.0,0.660924,...,11025.0,1000304,0.342515,0.752725,0.713727,1.28212,0.733268,0.722054,1.37461,29.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44051,0.602124,68.0,2.0,0.488843,5.966570,-1042.0,2017-09-08,44.0,0.0,0.579232,...,11027.0,6024193,0.545477,1.106370,1.209800,1.78063,0.551410,0.393084,1.22241,44.0
44052,0.604161,62.0,2.0,0.444603,1.042230,-1042.0,2022-03-18,11.0,1.0,0.552659,...,11025.0,6024277,0.196698,1.268020,1.197570,1.94878,1.084710,1.024220,1.91515,11.0
44053,0.651801,65.0,1.0,0.501976,3.082770,-1042.0,2015-02-25,92.0,0.0,0.654654,...,11025.0,6024345,0.448581,1.752880,1.989880,2.26531,0.849098,0.740336,1.58339,92.0
44054,0.652501,62.0,1.0,0.502078,-1.359400,-1086.0,2016-03-13,72.0,0.0,0.547722,...,11025.0,6024606,0.117782,1.578230,1.415020,2.89788,2.120820,2.048370,3.94747,72.0
44055,0.730108,64.0,2.0,0.506460,0.521898,-1042.0,2019-11-23,48.0,1.0,0.443076,...,11025.0,6024614,0.379711,1.029690,0.975871,1.66181,1.013530,0.921684,1.82692,48.0

In [ ]:
dti_confounds_full.to_csv('/IBu/UK_BB/CSV_brain/dti_confounds_full_clean.csv', index=False)
dti_confounds_nona.to_csv('/IBu/UK_BB/CSV_brain/dti_confounds_nona_clean.csv', index=False)

In [69]:
print(dti_confounds_nona.min())

Discrepancy between T1 brain image and standard-space brain template (linearly-aligned)         0.549554
Scanner transverse (Y) brain position                                                               52.0
Intensity scaling for dMRI                                                                           1.0
Discrepancy between T1 brain image and standard-space brain template (nonlinearly-aligned)      0.357276
Scanner lateral (X) brain position                                                              -41.0879
Scanner table position                                                                           -1197.0
Date of attending assessment centre                                                           2014-08-19
Number of dMRI outlier slices detected and corrected                                                 0.0
Increased search space in eddy current estimation used for dMRI                                      0.0
Discrepancy between dMRI brain image and T1 brain image                                         0.315992
Scanner longitudinal (Z) brain position                                                          -96.763
Standard deviation of apparent translation in the Y axis as measured by eddy                    0.118136
Volumetric scaling from T1 head image to standard space                                         0.801574
UK Biobank assessment centre                                                                     11025.0
eid                                                                                              1000046
Struct. motion                                                                                  -1.86047
Mean absolute head motion from dMRI                                                              0.30659
Median absolute head motion from dMRI                                                            0.27627
90th percentile of absolute head motion from dMRI                                               0.457104
Mean relative head motion from dMRI                                                             0.298725
Median relative head motion from dMRI                                                            0.24147
90th percentile of relative head motion from dMRI                                               0.447102
Number of slices that Eddy estimated to be outliers in dMRI data                                     0.0
dtype: object

In [70]:
#dti_confounds_nona.describe()
with pd.option_context('display.max_columns', None):
    display(dti_confounds_nona.describe())

,Discrepancy between T1 brain image and standard-space brain template (linearly-aligned),Scanner transverse (Y) brain position,Intensity scaling for dMRI,Discrepancy between T1 brain image and standard-space brain template (nonlinearly-aligned),Scanner lateral (X) brain position,Scanner table position,Number of dMRI outlier slices detected and corrected,Increased search space in eddy current estimation used for dMRI,Discrepancy between dMRI brain image and T1 brain image,Scanner longitudinal (Z) brain position,Standard deviation of apparent translation in the Y axis as measured by eddy,Volumetric scaling from T1 head image to standard space,UK Biobank assessment centre,eid,Struct. motion,Mean absolute head motion from dMRI,Median absolute head motion from dMRI,90th percentile of absolute head motion from dMRI,Mean relative head motion from dMRI,Median relative head motion from dMRI,90th percentile of relative head motion from dMRI,Number of slices that Eddy estimated to be outliers in dMRI data
count,44056.000000,44056.000000,44056.000000,44056.000000,44056.000000,44056.000000,44056.000000,44056.000000,44056.000000,44056.000000,44056.000000,44056.000000,44056.000000,4.405600e+04,44056.000000,44056.000000,44056.000000,44056.000000,44056.000000,44056.000000,44056.000000,44056.000000
mean,0.665388,66.680702,1.741238,0.494762,0.785665,-1053.209597,46.201494,0.297281,0.578783,-29.219508,1.028413,1.298283,11025.696931,3.519846e+06,0.338318,1.183172,1.087556,2.057707,1.176574,1.020061,2.336825,46.201494
std,0.041130,6.003777,0.438477,0.032001,3.113108,24.130151,34.061183,0.457066,0.073799,25.928813,0.459681,0.121941,0.866395,1.450047e+06,0.153719,0.487020,0.481623,0.864489,0.467837,0.412031,0.976632,34.061183
min,0.549554,52.000000,1.000000,0.357276,-41.087900,-1197.000000,0.000000,0.000000,0.315992,-96.763000,0.118136,0.801574,11025.000000,1.000046e+06,-1.860470,0.306590,0.276270,0.457104,0.298725,0.241470,0.447102,0.000000
25%,0.636167,62.000000,1.000000,0.472699,-1.099653,-1042.000000,26.000000,0.000000,0.526747,-44.997625,0.719453,1.209418,11025.000000,2.258702e+06,0.237057,0.859525,0.766605,1.485830,0.844720,0.722181,1.639267,26.000000
50%,0.659232,66.000000,2.000000,0.493868,0.676599,-1042.000000,39.000000,0.000000,0.575798,-34.974300,0.897225,1.295495,11025.000000,3.521582e+06,0.317252,1.064765,0.972115,1.841815,1.070920,0.938656,2.090825,39.000000
75%,0.687946,71.000000,2.000000,0.515418,2.575823,-1042.000000,56.000000,1.000000,0.627615,-23.117025,1.193283,1.383280,11027.000000,4.773980e+06,0.416319,1.372380,1.282012,2.376152,1.420020,1.250762,2.811210,56.000000
max,0.908677,96.000000,6.000000,0.668947,18.237200,-1020.000000,519.000000,1.000000,0.972697,124.458000,3.831990,1.941520,11028.000000,6.024614e+06,6.956990,7.504410,7.318660,14.523700,4.238030,3.624010,8.921570,519.000000

Diffusion tensor mode values measures between −1 and +1;

- approaches −1 if diffusion is occurring along a geometric plane,
- approaches +1 if diffusion is occurring along a single direction,
- approaches 0 when diffusion is orthotropic or isotropic [16].

More *positive* mode and high linear anisotropy indicate preferential diffusion along a single direction; this helps to see the structures which are arranged in linear form, for example, white matter tracts, which facilitate diffusion along one direction.

More *negative* mode and high planar anisotropy indicate preferential diffusion along a geometric plane; they display the structures that are **arranged in layers** that facilitate diffusion along a particular plane.

Diffusion tensor mode can be used to discriminate between different types of tissue structures, such as the presence of a single strong fiber in a voxel, vs multiple distinct fibers with different directions. For example, in the brain, white matter tracts are composed of bundles of axons that have high diffusion anisotropy and linear shape, while gray matter regions are composed of cell bodies and dendrites that have low diffusion anisotropy and spherical shape. If a voxel contains multiple fibers that cross or branch at different angles, the diffusion tensor mode will be closer to 1, indicating a planar shape.

## Remove redundant motion confounds

In [71]:
dti_confounds = dti_confounds_nona.drop(columns=['90th percentile of relative head motion from dMRI', '90th percentile of absolute head motion from dMRI',
                                            'Mean relative head motion from dMRI', 'Mean absolute head motion from dMRI'])

In [72]:
dti_confounds

,Discrepancy between T1 brain image and standard-space brain template (linearly-aligned),Scanner transverse (Y) brain position,Intensity scaling for dMRI,Discrepancy between T1 brain image and standard-space brain template (nonlinearly-aligned),Scanner lateral (X) brain position,Scanner table position,Date of attending assessment centre,Number of dMRI outlier slices detected and corrected,Increased search space in eddy current estimation used for dMRI,Discrepancy between dMRI brain image and T1 brain image,Scanner longitudinal (Z) brain position,Standard deviation of apparent translation in the Y axis as measured by eddy,Volumetric scaling from T1 head image to standard space,UK Biobank assessment centre,eid,Struct. motion,Median absolute head motion from dMRI,Median relative head motion from dMRI,Number of slices that Eddy estimated to be outliers in dMRI data
0,0.695184,62.0,1.0,0.487557,0.985166,-1089.0,2015-07-24,44.0,0.0,0.624899,26.99980,1.282250,1.25540,11025.0,1000046,0.166306,1.062120,1.196260,44.0
1,0.657209,61.0,2.0,0.484748,-1.590050,-1042.0,2019-11-19,96.0,1.0,0.588448,-37.57850,0.760415,1.43688,11025.0,1000054,0.488937,2.538270,0.996388,96.0
2,0.610478,63.0,2.0,0.466349,0.193689,-1042.0,2018-10-14,20.0,1.0,0.504682,-54.33320,2.468260,1.34341,11025.0,1000164,0.321029,1.972630,1.822410,20.0
3,0.598807,56.0,2.0,0.488218,2.003760,-1042.0,2017-11-15,44.0,0.0,0.700597,-29.35690,1.088640,1.32704,11025.0,1000203,0.299027,0.678971,1.127860,44.0
4,0.638328,65.0,2.0,0.543879,1.693270,-1042.0,2017-12-17,29.0,0.0,0.660924,-31.16950,0.639203,1.10518,11025.0,1000304,0.342515,0.713727,0.722054,29.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44051,0.602124,68.0,2.0,0.488843,5.966570,-1042.0,2017-09-08,44.0,0.0,0.579232,-32.68790,0.551415,1.10765,11027.0,6024193,0.545477,1.209800,0.393084,44.0
44052,0.604161,62.0,2.0,0.444603,1.042230,-1042.0,2022-03-18,11.0,1.0,0.552659,-43.83240,0.774871,1.51751,11025.0,6024277,0.196698,1.197570,1.024220,11.0
44053,0.651801,65.0,1.0,0.501976,3.082770,-1042.0,2015-02-25,92.0,0.0,0.654654,-34.47560,0.775610,1.35167,11025.0,6024345,0.448581,1.989880,0.740336,92.0
44054,0.652501,62.0,1.0,0.502078,-1.359400,-1086.0,2016-03-13,72.0,0.0,0.547722,-7.74656,1.687970,1.38344,11025.0,6024606,0.117782,1.415020,2.048370,72.0
44055,0.730108,64.0,2.0,0.506460,0.521898,-1042.0,2019-11-23,48.0,1.0,0.443076,-61.96160,0.708654,1.22325,11025.0,6024614,0.379711,0.975871,0.921684,48.0

### Convert Date to Unix and Dummy-encode Site

In [73]:
# Convert date
import datetime
dti_confounds_unix = dti_confounds.copy()
dti_confounds_unix['Date of attending assessment centre'] = pd.to_datetime(dti_confounds_unix['Date of attending assessment centre'], format="%Y-%m-%d")  #"%m/%d/%Y")
dti_confounds_unix['Date of attending assessment centre'] = dti_confounds_unix['Date of attending assessment centre'].apply(datetime.datetime.timestamp)
# Round values
dti_confounds_unix['Date of attending assessment centre'] = dti_confounds_unix['Date of attending assessment centre'].apply(int)
print(dti_confounds_unix['Date of attending assessment centre'])

0        1437652800
1        1574074800
2        1539428400
3        1510657200
4        1513422000
            ...
44051    1504785600
44052    1647514800
44053    1424775600
44054    1457780400
44055    1574420400
Name: Date of attending assessment centre, Length: 44056, dtype: int64

In [75]:
# Dummy encode site
dti_confounds_dummy = dti_confounds_unix.copy()
dti_confounds_dummy = pd.get_dummies(dti_confounds_dummy, columns=['UK Biobank assessment centre'], dtype=int)
dti_confounds_dummy

,Discrepancy between T1 brain image and standard-space brain template (linearly-aligned),Scanner transverse (Y) brain position,Intensity scaling for dMRI,Discrepancy between T1 brain image and standard-space brain template (nonlinearly-aligned),Scanner lateral (X) brain position,Scanner table position,Date of attending assessment centre,Number of dMRI outlier slices detected and corrected,Increased search space in eddy current estimation used for dMRI,Discrepancy between dMRI brain image and T1 brain image,...,Volumetric scaling from T1 head image to standard space,eid,Struct. motion,Median absolute head motion from dMRI,Median relative head motion from dMRI,Number of slices that Eddy estimated to be outliers in dMRI data,UK Biobank assessment centre_11025.0,UK Biobank assessment centre_11026.0,UK Biobank assessment centre_11027.0,UK Biobank assessment centre_11028.0
0,0.695184,62.0,1.0,0.487557,0.985166,-1089.0,1437652800,44.0,0.0,0.624899,...,1.25540,1000046,0.166306,1.062120,1.196260,44.0,1,0,0,0
1,0.657209,61.0,2.0,0.484748,-1.590050,-1042.0,1574074800,96.0,1.0,0.588448,...,1.43688,1000054,0.488937,2.538270,0.996388,96.0,1,0,0,0
2,0.610478,63.0,2.0,0.466349,0.193689,-1042.0,1539428400,20.0,1.0,0.504682,...,1.34341,1000164,0.321029,1.972630,1.822410,20.0,1,0,0,0
3,0.598807,56.0,2.0,0.488218,2.003760,-1042.0,1510657200,44.0,0.0,0.700597,...,1.32704,1000203,0.299027,0.678971,1.127860,44.0,1,0,0,0
4,0.638328,65.0,2.0,0.543879,1.693270,-1042.0,1513422000,29.0,0.0,0.660924,...,1.10518,1000304,0.342515,0.713727,0.722054,29.0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44051,0.602124,68.0,2.0,0.488843,5.966570,-1042.0,1504785600,44.0,0.0,0.579232,...,1.10765,6024193,0.545477,1.209800,0.393084,44.0,0,0,1,0
44052,0.604161,62.0,2.0,0.444603,1.042230,-1042.0,1647514800,11.0,1.0,0.552659,...,1.51751,6024277,0.196698,1.197570,1.024220,11.0,1,0,0,0
44053,0.651801,65.0,1.0,0.501976,3.082770,-1042.0,1424775600,92.0,0.0,0.654654,...,1.35167,6024345,0.448581,1.989880,0.740336,92.0,1,0,0,0
44054,0.652501,62.0,1.0,0.502078,-1.359400,-1086.0,1457780400,72.0,0.0,0.547722,...,1.38344,6024606,0.117782,1.415020,2.048370,72.0,1,0,0,0
44055,0.730108,64.0,2.0,0.506460,0.521898,-1042.0,1574420400,48.0,1.0,0.443076,...,1.22325,6024614,0.379711,0.975871,0.921684,48.0,1,0,0,0

In [76]:
dti_confounds_dummy.shape

(44056, 22)

In [ ]:
dti_confounds_dummy.to_csv('/IBu/UK_BB/brain/DTI/dti_confounds_final_set.csv', index=False)