In [5]:
import csv
import datetime
import pandas as pd
import numpy as np
import scipy.stats as ss
import time
from datetime import date, datetime
import ukbiobank.utils.utils
from ukbiobank.utils import fieldNamesToIds
from ukbiobank.utils import loadCsv
from ukbiobank.utils import addFields
from ukbiobank.utils.utils import getFieldnames
from ukbiobank.utils.utils import fieldIdsToNames

# T1w Modalities (IDPs)

- 1101	Regional grey matter volumes (FAST)	139
- 1102	Subcortical volumes (FIRST)	14
- 190	Freesurfer ASEG	99 - 2
- 195	Freesurfer BA exvivo	84
- 197	Freesurfer a2009s	444
- 196	Freesurfer DKT	186
- 194	Freesurfer desikan gw	70
- 193	Freesurfer desikan pial	66
- 192	Freesurfer desikan white	202
- 191	Freesurfer subsegmentation	121

T1 measures:
- Volume of GM
- Volume of subcortical structures
- Volume of CSF
- Volume of ventricles
- Volume of CC
- Volume of subcortical - whole brain
- Volume of Cerebellum!
- Mean intensity
- Area
- Mean thickness
- Grey-white contrast

In [ ]:
# Upload UK Bioabank csv
csv_path = '/IBu/UK_BB/ukbbdata/ukbb_oct23/ukb675684.csv'
ukb = ukbiobank.ukbio(ukb_csv=csv_path)

### 1. Regional grey matter volumes (FAST): 139

Get the fields

In [49]:
df_struct_fast = ukbiobank.utils.utils.loadCsv(ukbio=ukb, fields=['eid',
25888,
25889,
25822,
25823,
25892,
25880,
25881,
25864,
25865,
25838,
25839,
25840,
25841,
25900,
25902,
25901,
25903,
25905,
25904,
25844,
25845,
25830,
25831,
25862,
25863,
25846,
25847,
25782,
25783,
25870,
25871,
25886,
25887,
25893,
25894,
25915,
25917,
25916,
25792,
25793,
25790,
25791,
25808,
25809,
25810,
25811,
25812,
25813,
25784,
25785,
25828,
25829,
25832,
25833,
25826,
25827,
25824,
25825,
25852,
25853,
25788,
25789,
25802,
25803,
25804,
25805,
25806,
25807,
25860,
25861,
25876,
25877,
25884,
25885,
25836,
25837,
25848,
25849,
25850,
25851,
25866,
25867,
25868,
25869,
25872,
25873,
25814,
25815,
25794,
25795,
25842,
25843,
25882,
25883,
25834,
25835,
25786,
25787,
25816,
25817,
25798,
25799,
25800,
25801,
25874,
25875,
25818,
25819,
25820,
25821,
25854,
25855,
25856,
25857,
25858,
25859,
25796,
25797,
25878,
25879,
25895,
25896,
25897,
25899,
25898,
25909,
25911,
25910,
25912,
25914,
25913,
25906,
25908,
25907,
25890,
25891,
25918,
25919,
25920], instance=2)

In [50]:
struct_fast_names = ukbiobank.utils.utils.fieldIdsToNames(ukbio=ukb, df=df_struct_fast)

Drop NAs, remove instance number, and save

In [ ]:
struct_fast_names_nona = struct_fast_names.dropna(axis=0)
struct_fast_names_nona.columns = struct_fast_names_nona.columns.str.replace('-2.0', '')
struct_fast_names_nona.to_csv('/IBu/UK_BB/ML_DATASETS/Brain/T1/struct_fast_names_nona.csv', index=False)
struct_fast_names_nona

,Volume of grey matter in Frontal Operculum Cortex (right),"Volume of grey matter in Superior Temporal Gyrus, posterior division (left)","Volume of grey matter in Inferior Temporal Gyrus, anterior division (right)",Volume of grey matter in VIIIa Cerebellum (left),"Volume of grey matter in Temporal Fusiform Cortex, posterior division (right)",Volume of grey matter in Superior Parietal Lobule (right),Volume of grey matter in Pallidum (right),Volume of grey matter in Angular Gyrus (right),Volume of grey matter in Pallidum (left),Volume of grey matter in Middle Frontal Gyrus (right),...,"Volume of grey matter in Temporal Fusiform Cortex, anterior division (right)",Volume of grey matter in Crus I Cerebellum (left),Volume of grey matter in Subcallosal Cortex (left),Volume of grey matter in Parietal Operculum Cortex (left),Volume of grey matter in Temporal Pole (left),Volume of grey matter in Frontal Orbital Cortex (left),Volume of grey matter in Superior Frontal Gyrus (left),"Volume of grey matter in Supramarginal Gyrus, anterior division (left)","Volume of grey matter in Cingulate Gyrus, posterior division (left)",eid
3,1849.48,2330.05,1765.87,3542.26,3344.95,4536.62,41.3315,8929.71,12.4904,10382.40,...,1209.70,8878.44,3205.21,2100.42,10539.10,6377.08,9378.67,4008.36,5034.20,1000046
4,959.08,1978.47,1593.88,4136.04,2874.06,5455.30,28.2893,5010.44,10.0302,8310.00,...,1400.34,8539.43,2643.08,2238.51,7051.37,6418.69,7475.17,3119.57,4778.50,1000054
15,1606.56,2131.92,1614.23,3131.44,2388.73,4507.87,74.0692,5494.17,45.0013,7809.65,...,1375.17,10861.60,2661.49,1890.51,8938.17,6430.99,12459.20,3381.97,5189.92,1000164
19,1504.23,2966.36,1299.91,3742.27,3111.60,4515.67,35.7701,4621.10,19.9401,9688.47,...,1580.01,11153.70,3044.06,1995.41,8790.15,6651.85,10061.20,2475.51,5038.69,1000203
29,1366.23,2314.22,1777.53,4103.19,3394.36,6355.42,55.2012,8105.66,29.9801,10927.30,...,1701.30,12174.90,4049.88,2995.44,12224.20,7630.24,15563.00,4107.00,6826.32,1000304
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
502304,1148.41,2391.78,1816.73,3528.01,3243.20,4813.75,12.0406,4747.64,15.7196,7116.37,...,1487.39,10010.80,2524.61,1520.10,7855.99,6488.17,11186.60,2845.14,4588.27,6024277
502311,1142.14,2062.34,1630.33,3931.49,3036.68,7378.76,40.3396,4843.62,33.7405,9013.35,...,1201.49,8819.98,3086.17,1433.83,8698.79,5809.90,11689.00,3131.69,4452.23,6024345
502335,1475.81,2727.58,1281.33,4346.90,2762.96,4842.63,57.5987,6891.00,21.9986,11279.90,...,1408.84,12850.50,3076.61,1579.93,9199.59,6734.91,13789.60,4029.65,5384.46,6024581
502337,1063.54,2403.63,1877.12,2408.85,2758.84,4276.05,79.2794,6058.39,30.3785,7442.88,...,1408.13,8650.06,2584.02,1832.20,8190.05,5316.66,11540.80,3693.76,4302.55,6024606
502338,1324.45,2679.31,1245.99,3261.76,2884.78,2686.61,36.6416,5203.10,40.9210,8852.41,...,1205.73,11154.30,3315.28,1435.87,10539.90,6892.93,8514.73,2691.24,4542.78,6024614

### 2. Subcortical volumes (FIRST): 14

Get the fields

In [4]:
df_struct_sub_first = ukbiobank.utils.utils.loadCsv(ukbio=ukb, fields=['eid',
25023,
25024,
25021,
25022,
25013,
25014,
25019,
25020,
25017,
25018,
25015,
25016,
25011,
25012], instance=2)

In [5]:
struct_sub_first = addFields(ukbio=ukb, df=df_struct_sub_first, fields=['eid',
25023,
25024,
25021,
25022,
25013,
25014,
25019,
25020,
25017,
25018,
25015,
25016,
25011,
25012], instances=2)
struct_sub_first_names = ukbiobank.utils.utils.fieldIdsToNames(ukbio=ukb, df=df_struct_sub_first)

Drop NAs, remove instance number, and save

In [ ]:
struct_sub_first_names_nona = struct_sub_first_names.dropna(axis=0)
struct_sub_first_names_nona.columns = struct_sub_first_names_nona.columns.str.replace('-2.0', '')
struct_sub_first_names_nona.to_csv('/IBu/UK_BB/ML_DATASETS/Brain/T1/struct_sub_first_names_nona.csv', index=False)
struct_sub_first_names_nona

,Volume of pallidum (right),Volume of hippocampus (left),Volume of accumbens (left),Volume of putamen (right),Volume of caudate (left),Volume of accumbens (right),Volume of amygdala (right),Volume of thalamus (left),Volume of putamen (left),Volume of pallidum (left),Volume of amygdala (left),Volume of thalamus (right),Volume of caudate (right),Volume of hippocampus (right),eid
0,1784.0,3727.0,413.0,4582.0,2948.0,417.0,1245.0,8537.0,4428.0,1756.0,1169.0,8298.0,3038.0,4284.0,1000046
1,1786.0,3626.0,456.0,4137.0,3067.0,470.0,815.0,6532.0,3926.0,1658.0,1566.0,6436.0,3284.0,3377.0,1000054
2,1976.0,4024.0,569.0,5204.0,3433.0,349.0,1662.0,8113.0,4663.0,1828.0,1224.0,7794.0,3710.0,4082.0,1000164
3,1826.0,4320.0,455.0,4724.0,3069.0,396.0,1229.0,8259.0,4279.0,1786.0,1580.0,7639.0,3139.0,4278.0,1000203
4,1819.0,4370.0,624.0,5049.0,2883.0,465.0,1589.0,8451.0,4917.0,1687.0,1341.0,8184.0,3169.0,4094.0,1000304
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46376,1683.0,3781.0,472.0,4408.0,3205.0,370.0,1399.0,7643.0,4609.0,1601.0,1250.0,7309.0,3221.0,4439.0,6024277
46377,1660.0,3934.0,380.0,4648.0,3239.0,445.0,1211.0,6968.0,4656.0,1648.0,1375.0,6695.0,3322.0,3473.0,6024345
46378,2193.0,3842.0,528.0,5874.0,3622.0,157.0,1476.0,8261.0,6071.0,1851.0,1294.0,8044.0,3766.0,4405.0,6024581
46379,1436.0,3575.0,345.0,4477.0,3089.0,246.0,1407.0,7265.0,4516.0,1436.0,1071.0,7016.0,3308.0,3429.0,6024606
46380,1774.0,4130.0,501.0,5381.0,3658.0,401.0,1779.0,7571.0,5094.0,1811.0,1295.0,7251.0,3685.0,4006.0,6024614

### 3. Freesurfer ASEG

### 3.1. Freesurfer ASEG, Mean intensity whole brain: 41

#### 3.1.1 Freesurfer ASEG, Mean intensity whole brain

- 26501	Mean intensity of 3rd-Ventricle (whole brain)		
- 26502	Mean intensity of 4th-Ventricle (whole brain)		
- 26503	Mean intensity of 5th-Ventricle (whole brain)	
- 26504	Mean intensity of Brain-Stem (whole brain)		
- 26513	Mean intensity of CC-Anterior (whole brain)		
- 26511	Mean intensity of CC-Central (whole brain)		
- 26512	Mean intensity of CC-Mid-Anterior (whole brain)		
- 26510	Mean intensity of CC-Mid-Posterior (whole brain)		
- 26509	Mean intensity of CC-Posterior (whole brain)		
- 26505	Mean intensity of CSF (whole brain)		
- 26508	Mean intensity of Optic-Chiasm (whole brain)
- 26506	Mean intensity of WM-hypointensities (whole brain)			
- 26507	Mean intensity of non-WM-hypointensities (whole brain)

#### 3.1.2 Freesurfer ASEG, Mean intensity left/right

- 26548	Mean intensity of Accumbens-area (left hemisphere)			
- 26579	Mean intensity of Accumbens-area (right hemisphere)			
- 26547	Mean intensity of Amygdala (left hemisphere)			
- 26578	Mean intensity of Amygdala (right hemisphere)			
- 26543	Mean intensity of Caudate (left hemisphere)			
- 26574	Mean intensity of Caudate (right hemisphere)			
- 26541	Mean intensity of Cerebellum-Cortex (left hemisphere)			
- 26572	Mean intensity of Cerebellum-Cortex (right hemisphere)			
- 26540	Mean intensity of Cerebellum-White-Matter (left hemisphere)			
- 26571	Mean intensity of Cerebellum-White-Matter (right hemisphere)			
- 26546	Mean intensity of Hippocampus (left hemisphere)			
- 26577	Mean intensity of Hippocampus (right hemisphere)			
- 26539	Mean intensity of Inf-Lat-Vent (left hemisphere)			
- 26570	Mean intensity of Inf-Lat-Vent (right hemisphere)			
- 26538	Mean intensity of Lateral-Ventricle (left hemisphere)			
- 26569	Mean intensity of Lateral-Ventricle (right hemisphere)		
- 26545	Mean intensity of Pallidum (left hemisphere)			
- 26576	Mean intensity of Pallidum (right hemisphere)			
- 26544	Mean intensity of Putamen (left hemisphere)			
- 26575	Mean intensity of Putamen (right hemisphere)			
- 26542	Mean intensity of Thalamus-Proper (left hemisphere)			
- 26573	Mean intensity of Thalamus-Proper (right hemisphere)			
- 26549	Mean intensity of VentralDC (left hemisphere)			
- 26580	Mean intensity of VentralDC (right hemisphere)	
- 26551	Mean intensity of choroid-plexus (left hemisphere)			
- 26582	Mean intensity of choroid-plexus (right hemisphere)						
- 26550	Mean intensity of vessel (left hemisphere)			
- 26581	Mean intensity of vessel (right hemisphere)

Get the fields

In [23]:
df_struct_aseg_mean_intensity = ukbiobank.utils.utils.loadCsv(ukbio=ukb, fields=['eid',
26501,
26502,
26503,
26504,
26513,
26511,
26512,
26510,
26509,
26505,
26508,
26506,
26507,
26548,
26579,
26547,
26578,
26543,
26574,
26541,
26572,
26540,
26571,
26546,
26577,
26539,
26570,
26538,
26569,
26545,
26576,
26544,
26575,
26542,
26573,
26549,
26580,
26551,
26582,
26550,
26581], instance=2)

In [24]:
struct_aseg_mean_intensity = addFields(ukbio=ukb, df=df_struct_aseg_mean_intensity, fields=['eid',
26501,
26502,
26503,
26504,
26513,
26511,
26512,
26510,
26509,
26505,
26508,
26506,
26507,
26548,
26579,
26547,
26578,
26543,
26574,
26541,
26572,
26540,
26571,
26546,
26577,
26539,
26570,
26538,
26569,
26545,
26576,
26544,
26575,
26542,
26573,
26549,
26580,
26551,
26582,
26550,
26581], instances=2)
struct_aseg_mean_intensity_names = ukbiobank.utils.utils.fieldIdsToNames(ukbio=ukb, df=df_struct_aseg_mean_intensity)

Drop NAs, remove instance number, and save

In [ ]:
struct_aseg_mean_intensity_names_nona = struct_aseg_mean_intensity_names.dropna(axis=0)
struct_aseg_mean_intensity_names_nona.columns = struct_aseg_mean_intensity_names_nona.columns.str.replace('-2.0', '')
struct_aseg_mean_intensity_names_nona.to_csv('/IBu/UK_BB/ML_DATASETS/Brain/T1/struct_aseg_mean_intensity_names_nona.csv', index=False)
struct_aseg_mean_intensity_names_nona

,Mean intensity of Accumbens-area (left hemisphere),Mean intensity of Lateral-Ventricle (left hemisphere),Mean intensity of CC-Mid-Anterior (whole brain),Mean intensity of Amygdala (right hemisphere),Mean intensity of vessel (right hemisphere),Mean intensity of Pallidum (right hemisphere),Mean intensity of 3rd-Ventricle (whole brain),Mean intensity of Inf-Lat-Vent (right hemisphere),Mean intensity of VentralDC (left hemisphere),Mean intensity of Thalamus-Proper (left hemisphere),...,Mean intensity of Caudate (left hemisphere),Mean intensity of Lateral-Ventricle (right hemisphere),Mean intensity of choroid-plexus (left hemisphere),Mean intensity of Amygdala (left hemisphere),Mean intensity of Optic-Chiasm (whole brain),Mean intensity of Inf-Lat-Vent (left hemisphere),Mean intensity of WM-hypointensities (whole brain),Mean intensity of Hippocampus (right hemisphere),Mean intensity of Putamen (right hemisphere),eid
3,75.2076,23.1814,92.3936,69.6186,58.7778,98.6899,30.6954,41.9020,91.1229,86.6573,...,76.9755,23.6622,44.8340,69.3308,71.4468,44.0613,70.8413,67.4772,83.9630,1000046
4,77.2949,31.6531,91.3103,71.1303,61.0000,99.5360,34.4793,51.9030,90.4581,86.8542,...,80.0302,34.2050,52.2855,70.0879,75.3718,56.7500,69.3239,70.2990,86.0558,1000054
15,81.1295,33.0916,93.1493,69.2485,62.1667,98.5184,38.4206,43.5660,90.2356,87.5617,...,81.0945,34.0252,52.1115,71.6506,76.3333,50.8243,73.2276,69.1089,88.6570,1000164
19,77.2679,30.6161,93.0709,69.1919,63.2000,99.4498,35.5385,45.5000,90.4964,88.4241,...,80.1363,29.8727,48.7125,68.7277,80.6135,51.0599,69.9788,69.5705,87.2620,1000203
29,72.1055,21.4539,72.4501,65.4278,54.3889,93.2606,24.7231,33.4922,82.3269,78.2882,...,72.6764,21.3423,45.0705,66.6652,71.9497,40.3426,63.9981,63.3575,80.8312,1000304
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
502304,78.8994,31.6373,93.9744,68.5525,51.0101,99.7082,39.8209,47.7373,91.1975,87.1972,...,80.9358,32.5444,51.6856,72.0390,69.6792,44.9171,68.4955,68.5254,88.0634,6024277
502311,76.6772,30.0723,92.1790,70.2283,66.3333,99.5065,35.7365,42.6196,90.3710,85.5613,...,78.9437,31.8857,50.9621,71.4503,76.9282,48.4323,69.4631,69.8295,85.6574,6024345
502335,78.0168,30.8744,94.7916,68.7129,0.0000,98.7333,42.1145,47.6250,90.5423,89.4721,...,79.3590,32.4658,50.3158,70.7681,73.2889,42.4286,69.9366,69.4297,87.3254,6024581
502337,77.8107,27.9056,91.4936,70.6698,50.1707,97.5107,32.4482,46.0588,88.5217,85.4334,...,80.2628,28.3152,48.8849,72.0262,70.9018,47.9037,69.4574,66.9833,84.7402,6024606
502338,74.4113,24.2958,91.6372,69.9971,49.7917,97.7892,29.9820,38.1832,87.6075,83.0452,...,74.1385,24.8978,46.8024,67.4741,78.4228,37.4232,70.8856,67.9261,84.5489,6024614

### 3.2. Freesurfer ASEG, Volume whole brain: 54

#### 3.2.1 Freesurfer ASEG, Volume whole brain

- 26523	Volume of 3rd-Ventricle (whole brain)		
- 26524	Volume of 4th-Ventricle (whole brain)		
- 26525	Volume of 5th-Ventricle (whole brain)		
- 26526	Volume of Brain-Stem (whole brain)		
- 26514	Volume of BrainSeg (whole brain)		
- 26515	Volume of BrainSegNotVent (whole brain)		
- 26516	Volume of BrainSegNotVentSurf (whole brain)		
- 26535	Volume of CC-Anterior (whole brain)		
- 26533	Volume of CC-Central (whole brain)		
- 26534	Volume of CC-Mid-Anterior (whole brain)		
- 26532	Volume of CC-Mid-Posterior (whole brain)		
- 26531	Volume of CC-Posterior (whole brain)		
- 26527	Volume of CSF (whole brain)		
- 26521	Volume of EstimatedTotalIntraCranial (whole brain)			
- 26530	Volume of Optic-Chiasm (whole brain)			
- 26517	Volume of SubCortGray (whole brain)			
- 26519	Volume of SupraTentorial (whole brain)			
- 26520	Volume of SupraTentorialNotVent (whole brain)			
- 26518	Volume of TotalGray (whole brain)			
- 26522	Volume of VentricleChoroid (whole brain)			
- 26528	Volume of WM-hypointensities (whole brain)			
- 26529	Volume of non-WM-hypointensities (whole brain)

#### 3.2.2 Freesurfer ASEG, Volume left/right

- 26564	Volume of Accumbens-area (left hemisphere)		
- 26595	Volume of Accumbens-area (right hemisphere)		
- 26563	Volume of Amygdala (left hemisphere)		
- 26594	Volume of Amygdala (right hemisphere)	
- 26559	Volume of Caudate (left hemisphere)			
- 26590	Volume of Caudate (right hemisphere)			
- 26557	Volume of Cerebellum-Cortex (left hemisphere)			
- 26588	Volume of Cerebellum-Cortex (right hemisphere)			
- 26556	Volume of Cerebellum-White-Matter (left hemisphere)			
- 26587	Volume of Cerebellum-White-Matter (right hemisphere)			
- 26553	Volume of CerebralWhiteMatter (left hemisphere)			
- 26584	Volume of CerebralWhiteMatter (right hemisphere)			
- 26552	Volume of Cortex (left hemisphere)			
- 26583	Volume of Cortex (right hemisphere)			
- 26562	Volume of Hippocampus (left hemisphere)			
- 26593	Volume of Hippocampus (right hemisphere)			
- 26555	Volume of Inf-Lat-Vent (left hemisphere)			
- 26586	Volume of Inf-Lat-Vent (right hemisphere)			
- 26554	Volume of Lateral-Ventricle (left hemisphere)			
- 26585	Volume of Lateral-Ventricle (right hemisphere)			
- 26561	Volume of Pallidum (left hemisphere)			
- 26592	Volume of Pallidum (right hemisphere)			
- 26560	Volume of Putamen (left hemisphere)			
- 26591	Volume of Putamen (right hemisphere)			
- 26558	Volume of Thalamus-Proper (left hemisphere)			
- 26589	Volume of Thalamus-Proper (right hemisphere)			
- 26565	Volume of VentralDC (left hemisphere)			
- 26596	Volume of VentralDC (right hemisphere)			
- 26567	Volume of choroid-plexus (left hemisphere)			
- 26598	Volume of choroid-plexus (right hemisphere)			
- 26566	Volume of vessel (left hemisphere)			
- 26597	Volume of vessel (right hemisphere)

Get the fields

In [29]:
df_struct_aseg_volume = ukbiobank.utils.utils.loadCsv(ukbio=ukb, fields=['eid',
26523,
26524,
26525,
26526,
26514,
26515,
26516,
26535,
26533,
26534,
26532,
26531,
26527,
26521,
26530,
26517,
26519,
26520,
26518,
26522,
26528,
26529,
26564,
26595,
26563,
26594,
26559,
26590,
26557,
26588,
26556,
26587,
26553,
26584,
26552,
26583,
26562,
26593,
26555,
26586,
26554,
26585,
26561,
26592,
26560,
26591,
26558,
26589,
26565,
26596,
26567,
26598,
26566,
26597], instance=2)

In [30]:
struct_aseg_volume = addFields(ukbio=ukb, df=df_struct_aseg_volume, fields=['eid',
26523,
26524,
26525,
26526,
26514,
26515,
26516,
26535,
26533,
26534,
26532,
26531,
26527,
26521,
26530,
26517,
26519,
26520,
26518,
26522,
26528,
26529,
26564,
26595,
26563,
26594,
26559,
26590,
26557,
26588,
26556,
26587,
26553,
26584,
26552,
26583,
26562,
26593,
26555,
26586,
26554,
26585,
26561,
26592,
26560,
26591,
26558,
26589,
26565,
26596,
26567,
26598,
26566,
26597], instances=2)
struct_aseg_volume_names = ukbiobank.utils.utils.fieldIdsToNames(ukbio=ukb, df=df_struct_aseg_volume)

Drop NAs, remove instance number, and save

In [ ]:
struct_aseg_volume_names_nona = struct_aseg_volume_names.dropna(axis=0)
struct_aseg_volume_names_nona.columns = struct_aseg_volume_names_nona.columns.str.replace('-2.0', '')
struct_aseg_volume_names_nona.to_csv('/IBu/UK_BB/ML_DATASETS/Brain/T1/struct_aseg_volume_names_nona.csv', index=False)
struct_aseg_volume_names_nona

,Volume of Optic-Chiasm (whole brain),Volume of 5th-Ventricle (whole brain),Volume of Caudate (left hemisphere),Volume of Accumbens-area (right hemisphere),Volume of SubCortGray (whole brain),Volume of choroid-plexus (right hemisphere),Volume of Pallidum (right hemisphere),Volume of BrainSeg (whole brain),Volume of Hippocampus (left hemisphere),Volume of TotalGray (whole brain),...,Volume of CerebralWhiteMatter (right hemisphere),Volume of Lateral-Ventricle (right hemisphere),Volume of Brain-Stem (whole brain),Volume of CC-Central (whole brain),Volume of Inf-Lat-Vent (right hemisphere),Volume of Pallidum (left hemisphere),Volume of choroid-plexus (left hemisphere),Volume of Lateral-Ventricle (left hemisphere),Volume of CC-Posterior (whole brain),eid
3,136.7,0.0,2755.8,400.9,55249.0,790.1,2205.1,1290840.0,3729.6,699691.0,...,261589.0,14461.9,23562.2,445.4,354.7,2079.7,870.4,17078.0,1019.3,1000046
4,142.6,0.0,3020.9,437.0,47727.0,636.1,1860.8,1077360.0,3681.2,588454.0,...,222433.0,7052.3,18168.6,440.7,296.7,1876.6,541.2,9316.0,746.0,1000054
15,196.9,0.0,3246.3,515.6,55736.0,501.9,2328.2,1164330.0,3834.6,652255.0,...,227757.0,12973.2,21019.3,442.9,381.1,2319.0,468.3,13464.6,1002.4,1000164
19,159.7,0.0,2841.7,442.0,54698.0,413.0,1917.1,1211990.0,3881.4,645667.0,...,258292.0,8890.6,21727.3,686.3,210.6,2029.4,367.9,9178.4,1173.8,1000203
29,223.2,0.0,3093.9,597.3,58659.0,896.6,1808.6,1473580.0,4059.1,823178.0,...,288474.0,14249.7,22779.8,815.3,557.6,1888.1,763.6,17552.5,949.5,1000304
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
502304,101.7,0.0,2919.9,404.3,52634.0,459.4,1880.4,1090320.0,3952.4,601481.0,...,221390.0,8486.0,21043.0,504.4,311.8,1842.7,467.0,8273.3,942.6,6024277
502311,173.7,0.0,3177.0,477.8,52618.0,615.6,1940.5,1135940.0,3924.7,628643.0,...,233194.0,7089.6,18482.5,457.1,463.8,1932.9,414.0,8361.2,1060.4,6024345
502335,39.2,0.0,3373.7,506.1,59641.0,534.0,2293.6,1191640.0,4375.6,640811.0,...,245210.0,10385.2,23261.5,619.1,232.0,2119.0,688.7,10896.8,1162.1,6024581
502337,166.9,0.0,3275.2,429.3,50462.0,866.8,1761.4,1025620.0,3360.7,572541.0,...,197700.0,13294.3,20322.8,419.9,298.9,1621.8,887.8,13689.8,1013.3,6024606
502338,220.2,0.0,3994.3,580.0,60445.0,973.7,2028.5,1202340.0,4600.7,677643.0,...,219339.0,25949.3,20657.2,386.3,723.0,2138.8,792.5,26407.9,820.6,6024614

### 4. Freesurfer BA exvivo

#### 4.1. Freesurfer BA exvivo Area: 28

Get the fields

In [8]:
df_struct_ba_exvivo_area = ukbiobank.utils.utils.loadCsv(ukbio=ukb, fields=['eid',
27059,
27101,
27060,
27102,
27061,
27103,
27062,
27104,
27066,
27108,
27067,
27109,
27063,
27105,
27064,
27106,
27065,
27107,
27070,
27112,
27068,
27110,
27069,
27111,
27072,
27114,
27071,
27113], instance=2)

In [9]:
struct_ba_exvivo_area = addFields(ukbio=ukb, df=df_struct_ba_exvivo_area, fields=['eid',
27059,
27101,
27060,
27102,
27061,
27103,
27062,
27104,
27066,
27108,
27067,
27109,
27063,
27105,
27064,
27106,
27065,
27107,
27070,
27112,
27068,
27110,
27069,
27111,
27072,
27114,
27071,
27113], instances=2)
struct_ba_exvivo_area_names = ukbiobank.utils.utils.fieldIdsToNames(ukbio=ukb, df=df_struct_ba_exvivo_area)

Drop NAs, remove instance number, and save

In [ ]:
struct_ba_exvivo_area_names_nona = struct_ba_exvivo_area_names.dropna(axis=0)
struct_ba_exvivo_area_names_nona.columns = struct_ba_exvivo_area_names_nona.columns.str.replace('-2.0', '')
struct_ba_exvivo_area_names_nona.to_csv('/IBu/UK_BB/ML_DATASETS/Brain/T1/struct_ba_exvivo_area_names_nona.csv', index=False)
struct_ba_exvivo_area_names_nona

,Area of BA6 (left hemisphere),Area of BA45 (right hemisphere),Area of BA3b (left hemisphere),Area of BA2 (left hemisphere),Area of BA44 (left hemisphere),Area of BA4p (left hemisphere),Area of BA2 (right hemisphere),Area of V2 (left hemisphere),Area of BA44 (right hemisphere),Area of V2 (right hemisphere),...,Area of BA4p (right hemisphere),Area of BA4a (left hemisphere),Area of V1 (left hemisphere),Area of entorhinal (left hemisphere) (Field ID: 27072),Area of perirhinal (left hemisphere),Area of BA6 (right hemisphere),Area of MT (right hemisphere),Area of perirhinal (right hemisphere),Area of BA45 (left hemisphere),eid
3,6450.0,2356.0,1588.0,3234.0,1596.0,899.0,2450.0,5940.0,2249.0,5934.0,...,925.0,1089.0,2923.0,480.0,375.0,4946.0,1020.0,405.0,2053.0,1000046
4,7787.0,2441.0,1401.0,1426.0,1886.0,863.0,1311.0,5324.0,2325.0,5747.0,...,778.0,1071.0,2203.0,470.0,426.0,6057.0,1344.0,354.0,1923.0,1000054
15,5890.0,3101.0,1460.0,2250.0,1409.0,882.0,1857.0,4998.0,2286.0,5656.0,...,852.0,974.0,2286.0,459.0,436.0,5068.0,1322.0,411.0,1989.0,1000164
19,6128.0,2660.0,1407.0,2356.0,1368.0,813.0,1872.0,5637.0,2425.0,5694.0,...,809.0,1001.0,2372.0,560.0,459.0,4715.0,1155.0,427.0,1831.0,1000203
29,8547.0,3690.0,2035.0,3363.0,1552.0,1022.0,2413.0,7484.0,2740.0,6900.0,...,1088.0,1412.0,3383.0,486.0,433.0,7784.0,1961.0,536.0,2599.0,1000304
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
502304,5335.0,2322.0,1411.0,2134.0,1313.0,889.0,1887.0,4623.0,2017.0,4875.0,...,795.0,952.0,1878.0,472.0,426.0,4441.0,1150.0,450.0,1635.0,6024277
502311,6431.0,2547.0,1594.0,3140.0,1326.0,1029.0,2526.0,5580.0,2168.0,5667.0,...,909.0,1050.0,2642.0,541.0,416.0,5263.0,1459.0,399.0,2063.0,6024345
502335,5823.0,2515.0,1596.0,2632.0,1637.0,820.0,2164.0,5736.0,2361.0,5447.0,...,824.0,983.0,3013.0,419.0,301.0,5180.0,1319.0,351.0,1761.0,6024581
502337,5277.0,2513.0,1339.0,2350.0,1201.0,783.0,1956.0,5225.0,1827.0,5285.0,...,726.0,866.0,2269.0,412.0,361.0,4093.0,1514.0,378.0,1617.0,6024606
502338,5775.0,2793.0,1510.0,2026.0,1392.0,1080.0,1833.0,5269.0,2209.0,5003.0,...,972.0,1134.0,2346.0,509.0,382.0,5558.0,1198.0,408.0,1765.0,6024614

#### 4.2. Freesurfer BA exvivo Mean Thickness: 28

Get the fields

In [12]:
df_struct_ba_exvivo_mean_thickness = ukbiobank.utils.utils.loadCsv(ukbio=ukb, fields=['eid',
27073,
27115,
27074,
27116,
27075,
27117,
27076,
27118,
27080,
27122,
27081,
27123,
27077,
27119,
27078,
27120,
27079,
27121,
27084,
27126,
27082,
27124,
27083,
27125,
27086,
27128,
27085,
27127], instance=2)

In [13]:
struct_ba_exvivo_mean_thickness = addFields(ukbio=ukb, df=df_struct_ba_exvivo_mean_thickness, fields=['eid',
27073,
27115,
27074,
27116,
27075,
27117,
27076,
27118,
27080,
27122,
27081,
27123,
27077,
27119,
27078,
27120,
27079,
27121,
27084,
27126,
27082,
27124,
27083,
27125,
27086,
27128,
27085,
27127], instances=2)
struct_ba_exvivo_mean_thickness_names = ukbiobank.utils.utils.fieldIdsToNames(ukbio=ukb, df=df_struct_ba_exvivo_mean_thickness)

Drop NAs, remove instance number, and save

In [ ]:
struct_ba_exvivo_mean_thickness_names_nona = struct_ba_exvivo_mean_thickness_names.dropna(axis=0)
struct_ba_exvivo_mean_thickness_names_nona.columns = struct_ba_exvivo_mean_thickness_names_nona.columns.str.replace('-2.0', '')
struct_ba_exvivo_mean_thickness_names_nona.to_csv('/IBu/UK_BB/ML_DATASETS/Brain/T1/struct_ba_exvivo_mean_thickness_names_nona.csv', index=False)
struct_ba_exvivo_mean_thickness_names_nona

,Mean thickness of BA6 (left hemisphere),Mean thickness of BA3a (left hemisphere),Mean thickness of BA6 (right hemisphere),Mean thickness of BA1 (right hemisphere),Mean thickness of V2 (left hemisphere),Mean thickness of BA45 (right hemisphere),Mean thickness of BA44 (left hemisphere),Mean thickness of BA4p (right hemisphere),Mean thickness of V2 (right hemisphere),Mean thickness of BA3b (left hemisphere),...,Mean thickness of BA3b (right hemisphere),Mean thickness of BA2 (right hemisphere),Mean thickness of BA3a (right hemisphere),Mean thickness of BA44 (right hemisphere),Mean thickness of BA4a (left hemisphere),Mean thickness of entorhinal (left hemisphere) (Field ID: 27086),Mean thickness of BA45 (left hemisphere),Mean thickness of perirhinal (left hemisphere),Mean thickness of BA4a (right hemisphere),eid
3,3.081,1.975,2.947,2.370,2.020,2.685,2.981,2.722,2.006,2.138,...,1.975,2.415,1.972,2.864,2.820,2.653,2.613,2.905,2.493,1000046
4,2.795,2.459,2.579,2.689,2.048,2.573,2.837,2.297,1.826,2.643,...,2.746,2.597,2.466,2.700,2.454,2.731,2.779,2.595,2.214,1000054
15,3.030,2.138,2.962,2.426,2.092,2.755,2.790,3.024,2.148,2.067,...,2.042,2.474,2.027,2.760,3.252,3.319,2.663,3.452,3.022,1000164
19,2.980,1.964,3.020,2.583,1.873,2.715,2.992,2.758,1.831,2.158,...,2.047,2.474,1.899,2.991,2.818,3.264,2.798,3.305,2.614,1000203
29,2.800,1.980,2.828,2.383,2.121,2.631,2.752,2.477,2.203,2.128,...,2.024,2.403,2.063,2.955,2.543,2.948,2.392,3.284,2.623,1000304
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
502304,3.148,2.013,3.108,2.377,2.019,2.737,2.970,2.935,2.067,2.157,...,2.026,2.498,2.130,2.805,2.776,3.383,2.678,3.074,3.032,6024277
502311,2.834,1.802,2.916,2.432,1.915,2.603,2.767,2.128,2.090,1.946,...,1.972,2.297,1.846,2.717,2.695,3.047,2.440,2.677,2.762,6024345
502335,2.854,1.714,2.961,2.352,1.959,2.608,2.565,2.679,1.896,1.872,...,1.771,2.351,1.794,2.794,2.520,2.933,2.490,2.937,2.728,6024581
502337,2.735,1.652,2.709,2.023,1.966,2.554,2.650,2.309,2.020,1.922,...,1.813,2.136,1.628,2.666,2.815,3.371,2.620,2.532,2.454,6024606
502338,2.944,1.950,2.983,2.644,2.238,2.818,3.044,2.876,2.375,2.169,...,2.055,2.409,1.991,3.037,2.738,3.238,2.986,3.541,2.644,6024614

#### 4.3. Freesurfer BA exvivo Volume: 28

Get the fields

In [19]:
df_struct_ba_exvivo_volume = ukbiobank.utils.utils.loadCsv(ukbio=ukb, fields=['eid',
27087,
27129,
27088,
27130,
27089,
27131,
27090,
27132,
27094,
27136,
27095,
27137,
27091,
27133,
27092,
27134,
27093,
27135,
27098,
27140,
27096,
27138,
27097,
27139,
27100,
27142,
27099,
27141], instance=2)

In [20]:
struct_ba_exvivo_volume = addFields(ukbio=ukb, df=df_struct_ba_exvivo_volume, fields=['eid',
27087,
27129,
27088,
27130,
27089,
27131,
27090,
27132,
27094,
27136,
27095,
27137,
27091,
27133,
27092,
27134,
27093,
27135,
27098,
27140,
27096,
27138,
27097,
27139,
27100,
27142,
27099,
27141], instances=2)
struct_ba_exvivo_volume_names = ukbiobank.utils.utils.fieldIdsToNames(ukbio=ukb, df=df_struct_ba_exvivo_volume)

Drop NAs, remove instance number, and save

In [ ]:
struct_ba_exvivo_volume_names_nona = struct_ba_exvivo_volume_names.dropna(axis=0)
struct_ba_exvivo_volume_names_nona.columns = struct_ba_exvivo_volume_names_nona.columns.str.replace('-2.0', '')
struct_ba_exvivo_volume_names_nona.to_csv('/IBu/UK_BB/ML_DATASETS/Brain/T1/struct_ba_exvivo_volume_names_nona.csv', index=False)
struct_ba_exvivo_volume_names_nona

,Volume of BA4p (left hemisphere),Volume of BA44 (right hemisphere),Volume of BA2 (right hemisphere),Volume of perirhinal (right hemisphere),Volume of perirhinal (left hemisphere),Volume of BA1 (left hemisphere),Volume of BA3a (left hemisphere),Volume of BA45 (left hemisphere),Volume of entorhinal (left hemisphere) (Field ID: 27100),Volume of BA4a (left hemisphere),...,Volume of BA1 (right hemisphere),Volume of entorhinal (right hemisphere) (Field ID: 27142),Volume of MT (right hemisphere),Volume of V1 (left hemisphere),Volume of BA4p (right hemisphere),Volume of BA6 (right hemisphere),Volume of BA6 (left hemisphere),Volume of BA44 (left hemisphere),Volume of BA3b (left hemisphere),eid
3,2682.0,6607.0,5937.0,1813.0,1381.0,2211.0,1270.0,5718.0,1432.0,3643.0,...,1906.0,992.0,3091.0,5108.0,2439.0,17088.0,23030.0,5159.0,3822.0,1000046
4,2045.0,6938.0,4113.0,1459.0,1535.0,1615.0,1260.0,6164.0,1666.0,3063.0,...,1409.0,831.0,3428.0,3868.0,1746.0,17503.0,24732.0,6129.0,4092.0,1000054
15,2624.0,6541.0,4795.0,1913.0,2036.0,2057.0,1321.0,5991.0,1722.0,3802.0,...,1629.0,1172.0,3548.0,3906.0,2505.0,17441.0,21269.0,4545.0,3231.0,1000164
19,2470.0,7534.0,4968.0,1970.0,1865.0,1950.0,1180.0,5888.0,2240.0,3197.0,...,1712.0,1080.0,3093.0,3855.0,2162.0,16557.0,20981.0,4585.0,3329.0,1000203
29,2394.0,8980.0,5692.0,2118.0,1938.0,2400.0,1286.0,6230.0,1537.0,3906.0,...,1884.0,925.0,5419.0,6275.0,2611.0,23992.0,25369.0,4569.0,4780.0,1000304
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
502304,2361.0,6017.0,4767.0,2143.0,1660.0,1813.0,1119.0,4932.0,1860.0,3079.0,...,1480.0,1333.0,3032.0,3052.0,2245.0,15943.0,19194.0,4301.0,3345.0,6024277
502311,2419.0,6297.0,5898.0,1754.0,1361.0,1842.0,1191.0,5478.0,1979.0,3188.0,...,1794.0,1384.0,3321.0,3709.0,1858.0,17431.0,20530.0,3871.0,3538.0,6024345
502335,1960.0,7074.0,5083.0,1554.0,1136.0,1611.0,976.0,4913.0,1298.0,2766.0,...,1749.0,899.0,3592.0,4180.0,2192.0,17658.0,19181.0,4578.0,3120.0,6024581
502337,2199.0,5117.0,4276.0,1297.0,1183.0,1641.0,949.0,4942.0,1348.0,3005.0,...,1295.0,798.0,4227.0,3129.0,1643.0,12864.0,17261.0,3684.0,2970.0,6024606
502338,2878.0,7028.0,4488.0,2019.0,1888.0,1954.0,1264.0,6224.0,1830.0,3371.0,...,1731.0,1014.0,3471.0,4799.0,2662.0,19720.0,19974.0,4841.0,3614.0,6024614

### 5. Freesurfer a2009s

#### 5.1 Freesurfer a2009s Area: 148

Get the fields

In [4]:
df_struct_a2009s_area = ukbiobank.utils.utils.loadCsv(ukbio=ukb, fields=['eid',
27334,
27556,
27335,
27557,
27336,
27558,
27329,
27551,
27330,
27552,
27331,
27553,
27332,
27554,
27333,
27555,
27345,
27567,
27337,
27559,
27338,
27560,
27339,
27561,
27340,
27562,
27341,
27563,
27342,
27564,
27343,
27565,
27344,
27566,
27346,
27568,
27349,
27571,
27350,
27572,
27351,
27573,
27347,
27569,
27348,
27570,
27352,
27574,
27353,
27575,
27354,
27576,
27355,
27577,
27356,
27578,
27357,
27579,
27358,
27580,
27359,
27581,
27360,
27582,
27361,
27583,
27362,
27584,
27363,
27585,
27364,
27586,
27365,
27587,
27366,
27588,
27367,
27589,
27368,
27590,
27369,
27591,
27370,
27592,
27371,
27593,
27372,
27594,
27373,
27595,
27374,
27596,
27375,
27597,
27376,
27598,
27377,
27599,
27378,
27600,
27379,
27601,
27380,
27602,
27381,
27603,
27382,
27604,
27383,
27605,
27384,
27606,
27385,
27607,
27386,
27608,
27388,
27610,
27389,
27611,
27387,
27609,
27392,
27614,
27390,
27612,
27391,
27613,
27393,
27615,
27394,
27616,
27395,
27617,
27396,
27618,
27397,
27619,
27398,
27620,
27399,
27621,
27400,
27622,
27401,
27623,
27402,
27624], instance=2)

In [5]:
struct_a2009s_area = addFields(ukbio=ukb, df=df_struct_a2009s_area, fields=['eid',
27334,
27556,
27335,
27557,
27336,
27558,
27329,
27551,
27330,
27552,
27331,
27553,
27332,
27554,
27333,
27555,
27345,
27567,
27337,
27559,
27338,
27560,
27339,
27561,
27340,
27562,
27341,
27563,
27342,
27564,
27343,
27565,
27344,
27566,
27346,
27568,
27349,
27571,
27350,
27572,
27351,
27573,
27347,
27569,
27348,
27570,
27352,
27574,
27353,
27575,
27354,
27576,
27355,
27577,
27356,
27578,
27357,
27579,
27358,
27580,
27359,
27581,
27360,
27582,
27361,
27583,
27362,
27584,
27363,
27585,
27364,
27586,
27365,
27587,
27366,
27588,
27367,
27589,
27368,
27590,
27369,
27591,
27370,
27592,
27371,
27593,
27372,
27594,
27373,
27595,
27374,
27596,
27375,
27597,
27376,
27598,
27377,
27599,
27378,
27600,
27379,
27601,
27380,
27602,
27381,
27603,
27382,
27604,
27383,
27605,
27384,
27606,
27385,
27607,
27386,
27608,
27388,
27610,
27389,
27611,
27387,
27609,
27392,
27614,
27390,
27612,
27391,
27613,
27393,
27615,
27394,
27616,
27395,
27617,
27396,
27618,
27397,
27619,
27398,
27620,
27399,
27621,
27400,
27622,
27401,
27623,
27402,
27624], instances=2)
struct_a2009s_area_names = ukbiobank.utils.utils.fieldIdsToNames(ukbio=ukb, df=df_struct_a2009s_area)

Drop NAs, remove instance number, and save

In [ ]:
struct_a2009s_area_names_nona = struct_a2009s_area_names.dropna(axis=0)
struct_a2009s_area_names_nona.columns = struct_a2009s_area_names_nona.columns.str.replace('-2.0', '')
struct_a2009s_area_names_nona.to_csv('/IBu/UK_BB/ML_DATASETS/Brain/T1/struct_a2009s_area_names_nona.csv', index=False)
struct_a2009s_area_names_nona

,Area of S-temporal-transverse (left hemisphere),Area of S-calcarine (left hemisphere),Area of G-temp-sup-Plan-polar (left hemisphere),Area of G-front-middle (right hemisphere),Area of S-oc-temp-med+Lingual (left hemisphere),Area of G-cingul-Post-dorsal (left hemisphere),Area of S-interm-prim-Jensen (right hemisphere),Area of G-pariet-inf-Angular (right hemisphere),Area of G-insular-short (left hemisphere),Area of G-front-inf-Orbital (left hemisphere),...,Area of G-oc-temp-lat-fusifor (left hemisphere),Area of G+S-cingul-Mid-Ant (right hemisphere),Area of S-central (left hemisphere),Area of G-oc-temp-lat-fusifor (right hemisphere),Area of S-circular-insula-inf (right hemisphere),Area of G-front-inf-Triangul (left hemisphere),Area of Lat-Fis-ant-Vertical (left hemisphere),Area of G-insular-short (right hemisphere),Area of G-parietal-sup (left hemisphere),eid
3,283.0,1820.0,562.0,3146.0,1723.0,419.0,686.0,2144.0,500.0,322.0,...,1251.0,1097.0,2382.0,1475.0,888.0,636.0,165.0,648.0,2051.0,1000046
4,275.0,1547.0,389.0,2384.0,1693.0,310.0,242.0,1656.0,621.0,209.0,...,1415.0,830.0,1956.0,1508.0,816.0,718.0,200.0,468.0,1134.0,1000054
15,325.0,1694.0,539.0,2357.0,1305.0,366.0,247.0,1877.0,598.0,338.0,...,1246.0,851.0,2184.0,1032.0,869.0,674.0,259.0,562.0,1886.0,1000164
19,349.0,1679.0,482.0,3053.0,1421.0,379.0,443.0,1836.0,442.0,291.0,...,1408.0,883.0,2138.0,1205.0,912.0,613.0,223.0,432.0,1738.0,1000203
29,314.0,2167.0,578.0,2904.0,1604.0,535.0,251.0,2028.0,457.0,244.0,...,1575.0,1251.0,2771.0,1849.0,828.0,993.0,331.0,445.0,2457.0,1000304
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
502304,224.0,1367.0,407.0,2321.0,1479.0,325.0,189.0,1758.0,479.0,235.0,...,959.0,748.0,2181.0,1093.0,751.0,559.0,183.0,394.0,1844.0,6024277
502311,224.0,1949.0,463.0,3025.0,1178.0,514.0,436.0,2032.0,484.0,276.0,...,1030.0,1001.0,2588.0,1192.0,733.0,880.0,257.0,524.0,1977.0,6024345
502335,275.0,2174.0,574.0,2452.0,1327.0,405.0,439.0,2590.0,490.0,273.0,...,1556.0,968.0,2104.0,1588.0,851.0,699.0,130.0,620.0,1924.0,6024581
502337,309.0,1563.0,539.0,2114.0,1535.0,324.0,243.0,1751.0,405.0,212.0,...,1116.0,845.0,1958.0,1181.0,799.0,534.0,208.0,610.0,1602.0,6024606
502338,261.0,1776.0,531.0,2206.0,1207.0,410.0,52.0,1704.0,488.0,263.0,...,1013.0,1027.0,2510.0,1043.0,883.0,663.0,268.0,540.0,1623.0,6024614

#### 5.2 Freesurfer a2009s Mean thickness: 149

In [8]:
df_struct_a2009s_mean_thickness = ukbiobank.utils.utils.loadCsv(ukbio=ukb, fields=['eid',
27408,
27630,
27409,
27631,
27410,
27632,
27403,
27625,
27404,
27626,
27405,
27627,
27406,
27628,
27407,
27629,
27419,
27641,
27411,
27633,
27412,
27634,
27413,
27635,
27414,
27636,
27415,
27637,
27416,
27638,
27417,
27639,
27418,
27640,
27420,
27642,
27423,
27645,
27424,
27646,
27425,
27647,
27421,
27643,
27422,
27644,
27426,
27648,
27427,
27649,
27428,
27650,
27429,
27651,
27430,
27652,
27431,
27653,
27432,
27654,
27433,
27655,
27434,
27656,
27435,
27657,
27436,
27658,
27437,
27659,
27438,
27660,
27439,
27661,
27440,
27662,
27441,
27663,
27442,
27664,
27443,
27665,
27444,
27666,
27445,
27667,
27446,
27668,
27447,
27669,
27448,
27670,
27449,
27671,
27450,
27672,
27451,
27673,
27452,
27674,
27453,
27675,
27454,
27676,
27455,
27677,
27456,
27678,
27457,
27679,
27458,
27680,
27459,
27681,
27460,
27682,
27462,
27684,
27463,
27685,
27461,
27683,
27466,
27688,
27464,
27686,
27465,
27687,
27467,
27689,
27468,
27690,
27469,
27691,
27470,
27692,
27471,
27693,
27472,
27694,
27473,
27695,
27474,
27696,
27475,
27697,
27476,
27698], instance=2)

In [9]:
struct_a2009s_mean_thickness = addFields(ukbio=ukb, df=df_struct_a2009s_mean_thickness, fields=['eid',
27408,
27630,
27409,
27631,
27410,
27632,
27403,
27625,
27404,
27626,
27405,
27627,
27406,
27628,
27407,
27629,
27419,
27641,
27411,
27633,
27412,
27634,
27413,
27635,
27414,
27636,
27415,
27637,
27416,
27638,
27417,
27639,
27418,
27640,
27420,
27642,
27423,
27645,
27424,
27646,
27425,
27647,
27421,
27643,
27422,
27644,
27426,
27648,
27427,
27649,
27428,
27650,
27429,
27651,
27430,
27652,
27431,
27653,
27432,
27654,
27433,
27655,
27434,
27656,
27435,
27657,
27436,
27658,
27437,
27659,
27438,
27660,
27439,
27661,
27440,
27662,
27441,
27663,
27442,
27664,
27443,
27665,
27444,
27666,
27445,
27667,
27446,
27668,
27447,
27669,
27448,
27670,
27449,
27671,
27450,
27672,
27451,
27673,
27452,
27674,
27453,
27675,
27454,
27676,
27455,
27677,
27456,
27678,
27457,
27679,
27458,
27680,
27459,
27681,
27460,
27682,
27462,
27684,
27463,
27685,
27461,
27683,
27466,
27688,
27464,
27686,
27465,
27687,
27467,
27689,
27468,
27690,
27469,
27691,
27470,
27692,
27471,
27693,
27472,
27694,
27473,
27695,
27474,
27696,
27475,
27697,
27476,
27698], instances=2)
struct_a2009s_mean_thickness_names = ukbiobank.utils.utils.fieldIdsToNames(ukbio=ukb, df=df_struct_a2009s_mean_thickness)

Drop NAs, remove instance number, and save

In [ ]:
struct_a2009s_mean_thickness_names_nona = struct_a2009s_mean_thickness_names.dropna(axis=0)
struct_a2009s_mean_thickness_names_nona.columns = struct_a2009s_mean_thickness_names_nona.columns.str.replace('-2.0', '')
struct_a2009s_mean_thickness_names_nona.to_csv('/IBu/UK_BB/ML_DATASETS/Brain/T1/struct_a2009s_mean_thickness_names_nona.csv', index=False)
struct_a2009s_mean_thickness_names_nona

,Mean thickness of G-orbital (right hemisphere),Mean thickness of G-Ins-lg+S-cent-ins (right hemisphere),Mean thickness of G-temp-sup-Plan-polar (right hemisphere),Mean thickness of G-oc-temp-med-Parahip (left hemisphere),Mean thickness of S-front-inf (left hemisphere),Mean thickness of G-postcentral (left hemisphere),Mean thickness of G-parietal-sup (right hemisphere),Mean thickness of S-temporal-inf (right hemisphere),Mean thickness of G-pariet-inf-Angular (right hemisphere),Mean thickness of S-circular-insula-inf (left hemisphere),...,Mean thickness of G-precentral (left hemisphere),Mean thickness of S-parieto-occipital (left hemisphere),Mean thickness of G-cingul-Post-dorsal (right hemisphere),Mean thickness of S-temporal-transverse (left hemisphere),Mean thickness of S-central (left hemisphere),Mean thickness of S-circular-insula-ant (right hemisphere),Mean thickness of Pole-temporal (right hemisphere),Mean thickness of S-temporal-sup (left hemisphere),Mean thickness of S-circular-insula-sup (left hemisphere),eid
3,2.871,3.567,3.613,2.796,2.616,2.425,2.607,2.816,2.821,2.979,...,3.285,2.640,3.196,2.391,2.206,2.878,3.456,2.729,2.975,1000046
4,2.581,3.185,2.734,2.581,2.429,2.755,2.659,2.044,2.735,3.016,...,2.314,2.414,3.333,2.340,2.421,3.338,3.121,2.712,2.678,1000054
15,3.137,3.127,3.446,3.297,2.451,2.417,2.756,2.775,2.936,2.849,...,3.238,2.312,3.062,2.330,2.295,3.106,3.313,2.606,2.853,1000164
19,2.999,3.526,2.982,3.089,2.620,2.505,2.721,2.699,2.786,2.598,...,3.082,2.519,3.024,2.571,2.291,3.108,3.355,2.718,2.904,1000203
29,3.045,3.560,3.524,3.136,2.417,2.435,2.476,2.774,2.701,3.238,...,2.454,2.601,3.109,2.407,2.178,3.279,3.296,2.719,2.838,1000304
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
502304,2.894,2.878,3.151,3.119,2.491,2.383,2.592,2.730,2.929,2.807,...,3.146,2.432,3.293,3.027,2.231,2.912,3.580,2.800,2.846,6024277
502311,2.881,3.148,3.685,2.688,2.397,2.069,2.584,2.746,2.730,2.974,...,2.802,2.321,3.221,1.929,1.944,3.177,3.429,2.588,2.694,6024345
502335,2.602,3.086,3.331,2.946,2.267,1.966,2.597,2.094,2.712,2.516,...,2.897,2.375,3.321,2.463,1.837,3.067,3.235,2.514,2.594,6024581
502337,2.813,2.637,2.793,2.900,2.306,2.092,2.294,2.237,2.762,2.319,...,2.865,2.316,2.890,2.378,1.958,2.659,3.497,2.411,2.685,6024606
502338,3.228,3.651,3.862,3.506,2.722,2.452,2.522,2.835,2.807,3.017,...,2.934,2.595,3.188,2.431,2.330,3.746,3.594,2.697,3.073,6024614

#### 5.3 Freesurfer a2009s volume G+S: 148

In [12]:
df_struct_a2009s_volume = ukbiobank.utils.utils.loadCsv(ukbio=ukb, fields=['eid',
27482,
27704,
27483,
27705,
27484,
27706,
27477,
27699,
27478,
27700,
27479,
27701,
27480,
27702,
27481,
27703,
27493,
27715,
27485,
27707,
27486,
27708,
27487,
27709,
27488,
27710,
27489,
27711,
27490,
27712,
27491,
27713,
27492,
27714,
27494,
27716,
27497,
27719,
27498,
27720,
27499,
27721,
27495,
27717,
27496,
27718,
27500,
27722,
27501,
27723,
27502,
27724,
27503,
27725,
27504,
27726,
27505,
27727,
27506,
27728,
27507,
27729,
27508,
27730,
27509,
27731,
27510,
27732,
27511,
27733,
27512,
27734,
27513,
27735,
27514,
27736,
27515,
27737,
27516,
27738,
27517,
27739,
27518,
27740,
27519,
27741,
27520,
27742,
27521,
27743,
27522,
27744,
27523,
27745,
27524,
27746,
27525,
27747,
27526,
27748,
27527,
27749,
27528,
27750,
27529,
27751,
27530,
27752,
27531,
27753,
27532,
27754,
27533,
27755,
27534,
27756,
27536,
27758,
27537,
27759,
27535,
27757,
27540,
27762,
27538,
27760,
27539,
27761,
27541,
27763,
27542,
27764,
27543,
27765,
27544,
27766,
27545,
27767,
27546,
27768,
27547,
27769,
27548,
27770,
27549,
27771,
27550,
27772], instance=2)

In [13]:
struct_a2009s_volume = addFields(ukbio=ukb, df=df_struct_a2009s_volume , fields=['eid',
27482,
27704,
27483,
27705,
27484,
27706,
27477,
27699,
27478,
27700,
27479,
27701,
27480,
27702,
27481,
27703,
27493,
27715,
27485,
27707,
27486,
27708,
27487,
27709,
27488,
27710,
27489,
27711,
27490,
27712,
27491,
27713,
27492,
27714,
27494,
27716,
27497,
27719,
27498,
27720,
27499,
27721,
27495,
27717,
27496,
27718,
27500,
27722,
27501,
27723,
27502,
27724,
27503,
27725,
27504,
27726,
27505,
27727,
27506,
27728,
27507,
27729,
27508,
27730,
27509,
27731,
27510,
27732,
27511,
27733,
27512,
27734,
27513,
27735,
27514,
27736,
27515,
27737,
27516,
27738,
27517,
27739,
27518,
27740,
27519,
27741,
27520,
27742,
27521,
27743,
27522,
27744,
27523,
27745,
27524,
27746,
27525,
27747,
27526,
27748,
27527,
27749,
27528,
27750,
27529,
27751,
27530,
27752,
27531,
27753,
27532,
27754,
27533,
27755,
27534,
27756,
27536,
27758,
27537,
27759,
27535,
27757,
27540,
27762,
27538,
27760,
27539,
27761,
27541,
27763,
27542,
27764,
27543,
27765,
27544,
27766,
27545,
27767,
27546,
27768,
27547,
27769,
27548,
27770,
27549,
27771,
27550,
27772], instances=2)
struct_a2009s_volume_names = ukbiobank.utils.utils.fieldIdsToNames(ukbio=ukb, df=df_struct_a2009s_volume)

Drop NAs, remove instance number, and save

In [ ]:
struct_a2009s_volume_names_nona = struct_a2009s_volume_names.dropna(axis=0)
struct_a2009s_volume_names_nona.columns = struct_a2009s_volume_names_nona.columns.str.replace('-2.0', '')
struct_a2009s_volume_names_nona.to_csv('/IBu/UK_BB/ML_DATASETS/Brain/T1/struct_a2009s_volume_names_nona.csv', index=False)
struct_a2009s_volume_names_nona

,Volume of S-circular-insula-ant (left hemisphere),Volume of G-temporal-middle (right hemisphere),Volume of G+S-cingul-Mid-Ant (left hemisphere),Volume of S-precentral-inf-part (left hemisphere),Volume of S-calcarine (right hemisphere),Volume of G+S-cingul-Mid-Post (right hemisphere),Volume of G-rectus (left hemisphere),Volume of G-oc-temp-med-Parahip (left hemisphere),Volume of S-subparietal (left hemisphere),Volume of G-parietal-sup (right hemisphere),...,Volume of G+S-cingul-Mid-Post (left hemisphere),Volume of G-temporal-middle (left hemisphere),Volume of G-cingul-Post-ventral (right hemisphere),Volume of G+S-subcentral (left hemisphere),Volume of G-subcallosal (right hemisphere),Volume of G-pariet-inf-Angular (left hemisphere),Volume of G-insular-short (right hemisphere),Volume of G-parietal-sup (left hemisphere),Volume of S-postcentral (left hemisphere),eid
3,988.0,8717.0,3684.0,3028.0,3775.0,2747.0,2693.0,2763.0,1457.0,6592.0,...,3254.0,9273.0,954.0,2659.0,1192.0,5793.0,2635.0,7487.0,6669.0,1000046
4,802.0,6392.0,2746.0,3577.0,2501.0,2716.0,2540.0,3126.0,963.0,3306.0,...,2711.0,7063.0,562.0,3782.0,717.0,5184.0,2235.0,3611.0,3045.0,1000054
15,845.0,7520.0,2647.0,2454.0,3446.0,2806.0,2745.0,3674.0,1550.0,4095.0,...,3115.0,6514.0,718.0,2900.0,612.0,6220.0,2539.0,5925.0,3702.0,1000164
19,798.0,6479.0,2943.0,2632.0,2535.0,2888.0,2987.0,4339.0,1439.0,6037.0,...,2646.0,7649.0,725.0,2829.0,930.0,5152.0,2124.0,6045.0,3960.0,1000203
29,879.0,11642.0,4200.0,4643.0,3951.0,4804.0,3135.0,3579.0,1810.0,7252.0,...,3495.0,8683.0,866.0,4254.0,1353.0,6895.0,2237.0,7551.0,5718.0,1000304
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
502304,680.0,6834.0,2072.0,2159.0,2454.0,2122.0,1924.0,3885.0,1301.0,5623.0,...,2183.0,8002.0,605.0,3011.0,822.0,6084.0,1860.0,5884.0,3901.0,6024277
502311,854.0,8579.0,2335.0,2823.0,2426.0,2801.0,2281.0,3350.0,1225.0,5614.0,...,2777.0,6671.0,833.0,2913.0,857.0,5442.0,2257.0,5887.0,5333.0,6024345
502335,889.0,8550.0,2424.0,2526.0,3465.0,2650.0,2623.0,3045.0,1541.0,5663.0,...,2443.0,7980.0,582.0,3307.0,668.0,6570.0,2114.0,5746.0,4515.0,6024581
502337,801.0,8730.0,2163.0,2139.0,2457.0,2310.0,2626.0,3130.0,1318.0,4079.0,...,2504.0,7392.0,585.0,2973.0,757.0,5063.0,2060.0,4873.0,3970.0,6024606
502338,981.0,7731.0,2020.0,2639.0,3054.0,3235.0,2910.0,4305.0,1418.0,3917.0,...,3030.0,8086.0,1057.0,3192.0,866.0,4825.0,2397.0,5102.0,3778.0,6024614

### 6. Freesurfer DKT

#### 6.1 Freesurfer DKT area: 62

Get the fields

In [16]:
df_struct_dkt_area = ukbiobank.utils.utils.loadCsv(ukbio=ukb, fields=['eid',
27143,
27236,
27144,
27237,
27145,
27238,
27146,
27239,
27147,
27240,
27148,
27241,
27149,
27242,
27173,
27266,
27150,
27243,
27151,
27244,
27152,
27245,
27153,
27246,
27154,
27247,
27155,
27248,
27157,
27250,
27156,
27249,
27158,
27251,
27159,
27252,
27160,
27253,
27161,
27254,
27162,
27255,
27163,
27256,
27164,
27257,
27165,
27258,
27166,
27259,
27167,
27260,
27168,
27261,
27169,
27262,
27170,
27263,
27171,
27264,
27172,
27265], instance=2)

In [17]:
struct_dkt_area = addFields(ukbio=ukb, df=df_struct_dkt_area , fields=['eid',
27143,
27236,
27144,
27237,
27145,
27238,
27146,
27239,
27147,
27240,
27148,
27241,
27149,
27242,
27173,
27266,
27150,
27243,
27151,
27244,
27152,
27245,
27153,
27246,
27154,
27247,
27155,
27248,
27157,
27250,
27156,
27249,
27158,
27251,
27159,
27252,
27160,
27253,
27161,
27254,
27162,
27255,
27163,
27256,
27164,
27257,
27165,
27258,
27166,
27259,
27167,
27260,
27168,
27261,
27169,
27262,
27170,
27263,
27171,
27264,
27172,
27265], instances=2)
struct_dkt_area_names = ukbiobank.utils.utils.fieldIdsToNames(ukbio=ukb, df=df_struct_dkt_area)

Drop NAs, remove instance number, and save

In [ ]:
struct_dkt_area_names_nona = struct_dkt_area_names.dropna(axis=0)
struct_dkt_area_names_nona.columns = struct_dkt_area_names_nona.columns.str.replace('-2.0', '')
struct_dkt_area_names_nona.to_csv('/IBu/UK_BB/ML_DATASETS/Brain/T1/struct_dkt_area_names_nona.csv', index=False)
struct_dkt_area_names_nona

,Area of postcentral (right hemisphere) (Field ID: 27255),Area of parsorbitalis (left hemisphere) (Field ID: 27159),Area of precuneus (right hemisphere) (Field ID: 27258),Area of paracentral (right hemisphere) (Field ID: 27250),Area of parstriangularis (right hemisphere) (Field ID: 27253),Area of lateraloccipital (left hemisphere) (Field ID: 27151),Area of supramarginal (right hemisphere) (Field ID: 27264),Area of pericalcarine (left hemisphere) (Field ID: 27161),Area of rostralanteriorcingulate (right hemisphere) (Field ID: 27259),Area of parstriangularis (left hemisphere) (Field ID: 27160),...,Area of parahippocampal (left hemisphere) (Field ID: 27156),Area of lateraloccipital (right hemisphere) (Field ID: 27244),Area of superiortemporal (left hemisphere) (Field ID: 27170),Area of posteriorcingulate (left hemisphere) (Field ID: 27163),Area of entorhinal (right hemisphere) (Field ID: 27239),Area of transversetemporal (left hemisphere) (Field ID: 27172),Area of superiorfrontal (left hemisphere) (Field ID: 27168),Area of superiorparietal (left hemisphere) (Field ID: 27169),Area of supramarginal (left hemisphere) (Field ID: 27171),eid
3,4855.0,700.0,4185.0,1641.0,1093.0,5285.0,3909.0,1660.0,1147.0,1490.0,...,733.0,4498.0,4910.0,1475.0,352.0,465.0,8469.0,4538.0,3609.0,1000046
4,3261.0,619.0,3440.0,1305.0,1291.0,4799.0,2485.0,1272.0,687.0,1449.0,...,780.0,5061.0,4334.0,1107.0,335.0,369.0,7985.0,2584.0,2808.0,1000054
15,4059.0,683.0,3639.0,1658.0,1767.0,4682.0,3163.0,1321.0,882.0,1541.0,...,681.0,4815.0,4706.0,1336.0,405.0,407.0,7611.0,3710.0,3220.0,1000164
19,3976.0,661.0,3646.0,1688.0,1466.0,4693.0,3364.0,1299.0,766.0,1453.0,...,735.0,4734.0,5025.0,1235.0,399.0,434.0,8052.0,3896.0,3353.0,1000203
29,5138.0,747.0,5244.0,2107.0,2080.0,7209.0,3903.0,1918.0,1112.0,2064.0,...,669.0,6312.0,5975.0,1445.0,533.0,434.0,10024.0,5195.0,5893.0,1000304
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
502304,3862.0,613.0,3722.0,1290.0,1251.0,3939.0,3262.0,1075.0,635.0,1325.0,...,722.0,4045.0,4223.0,1066.0,409.0,356.0,6911.0,4027.0,3164.0,6024277
502311,4534.0,694.0,4305.0,1383.0,1359.0,4291.0,3677.0,1550.0,792.0,1683.0,...,656.0,5144.0,4441.0,1195.0,298.0,421.0,7927.0,4531.0,3296.0,6024345
502335,4375.0,642.0,3631.0,1567.0,1426.0,4861.0,3740.0,1789.0,670.0,1393.0,...,629.0,4634.0,4639.0,1110.0,330.0,418.0,7498.0,3887.0,3574.0,6024581
502337,3972.0,499.0,3588.0,1469.0,1314.0,4725.0,2954.0,1277.0,653.0,1228.0,...,640.0,4698.0,4722.0,1137.0,294.0,411.0,6804.0,3760.0,3377.0,6024606
502338,4006.0,612.0,3482.0,1803.0,1531.0,5040.0,2717.0,1323.0,915.0,1476.0,...,609.0,4612.0,4873.0,1292.0,375.0,380.0,7828.0,3494.0,2906.0,6024614

#### 6.2 Freesurfer DKT Mean thickness: 62

In [19]:
df_struct_dkt_mean_thickness = ukbiobank.utils.utils.loadCsv(ukbio=ukb, fields=['eid',
27174,
27267,
27175,
27268,
27176,
27269,
27177,
27270,
27178,
27271,
27179,
27272,
27180,
27273,
27204,
27297,
27181,
27274,
27182,
27275,
27183,
27276,
27184,
27277,
27185,
27278,
27186,
27279,
27188,
27281,
27187,
27280,
27189,
27282,
27190,
27283,
27191,
27284,
27192,
27285,
27193,
27286,
27194,
27287,
27195,
27288,
27196,
27289,
27197,
27290,
27198,
27291,
27199,
27292,
27200,
27293,
27201,
27294,
27202,
27295,
27203,
27296], instance=2)

Drop NAs, remove instance number, and save

In [ ]:
struct_dkt_mean_thickness_names = ukbiobank.utils.utils.fieldIdsToNames(ukbio=ukb, df=df_struct_dkt_mean_thickness)
struct_dkt_mean_thickness_names_nona = struct_dkt_mean_thickness_names.dropna(axis=0)
struct_dkt_mean_thickness_names_nona.columns = struct_dkt_mean_thickness_names_nona.columns.str.replace('-2.0', '')
struct_dkt_mean_thickness_names_nona.to_csv('/IBu/UK_BB/ML_DATASETS/Brain/T1/struct_dkt_mean_thickness_names_nona.csv', index=False)
struct_dkt_mean_thickness_names_nona

,Mean thickness of paracentral (left hemisphere) (Field ID: 27188),Mean thickness of parahippocampal (right hemisphere) (Field ID: 27280),Mean thickness of superiorfrontal (left hemisphere) (Field ID: 27199),Mean thickness of insula (right hemisphere) (Field ID: 27297),Mean thickness of precuneus (left hemisphere) (Field ID: 27196),Mean thickness of superiorparietal (left hemisphere) (Field ID: 27200),Mean thickness of rostralmiddlefrontal (left hemisphere) (Field ID: 27198),Mean thickness of fusiform (right hemisphere) (Field ID: 27271),Mean thickness of inferiortemporal (left hemisphere) (Field ID: 27180),Mean thickness of postcentral (left hemisphere) (Field ID: 27193),...,Mean thickness of transversetemporal (left hemisphere) (Field ID: 27203),Mean thickness of lateralorbitofrontal (right hemisphere) (Field ID: 27276),Mean thickness of parahippocampal (left hemisphere) (Field ID: 27187),Mean thickness of rostralmiddlefrontal (right hemisphere) (Field ID: 27291),Mean thickness of parsorbitalis (right hemisphere) (Field ID: 27283),Mean thickness of caudalanteriorcingulate (right hemisphere) (Field ID: 27267),Mean thickness of precuneus (right hemisphere) (Field ID: 27289),Mean thickness of lateraloccipital (right hemisphere) (Field ID: 27275),Mean thickness of lateralorbitofrontal (left hemisphere) (Field ID: 27183),eid
3,2.681,2.567,2.916,3.207,2.752,2.613,2.630,2.855,2.972,2.378,...,2.408,2.796,2.410,2.621,2.819,2.658,2.687,2.361,2.848,1000046
4,2.533,2.286,2.975,3.114,2.586,2.479,2.674,2.724,2.885,2.713,...,2.389,2.566,2.501,2.479,2.693,2.843,2.494,2.137,2.717,1000054
15,2.908,3.068,2.872,3.189,2.688,2.389,2.541,2.950,2.863,2.373,...,2.551,2.837,3.182,2.618,3.089,2.637,2.623,2.472,2.720,1000164
19,2.706,2.675,3.014,3.254,2.696,2.453,2.651,2.836,2.922,2.436,...,2.617,2.861,3.000,2.551,2.679,2.514,2.772,2.187,2.897,1000203
29,2.737,2.905,2.902,3.164,2.853,2.395,2.480,2.925,3.167,2.394,...,2.846,2.914,2.884,2.568,2.966,2.885,2.712,2.454,2.995,1000304
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
502304,2.715,2.895,3.061,3.112,2.725,2.530,2.727,3.040,2.991,2.392,...,2.608,2.753,2.899,2.752,2.995,2.811,2.769,2.348,2.729,6024277
502311,2.403,3.080,2.867,3.095,2.441,2.320,2.500,2.985,2.909,2.136,...,2.346,2.786,2.679,2.562,2.850,2.840,2.459,2.263,2.705,6024345
502335,2.498,2.455,2.805,2.955,2.545,2.292,2.525,2.648,2.828,2.013,...,2.063,2.621,2.598,2.588,2.802,1.870,2.563,2.165,2.712,6024581
502337,2.459,2.535,2.590,2.702,2.564,2.237,2.394,2.824,2.914,2.086,...,2.473,2.707,2.808,2.483,2.744,2.114,2.471,2.204,2.753,6024606
502338,2.618,3.369,2.861,3.521,2.596,2.434,2.641,3.257,3.071,2.356,...,2.950,3.191,3.080,2.774,3.106,2.683,2.591,2.582,3.073,6024614

#### 6.3 Freesurfer DKT Volume: 62

In [23]:
df_struct_dkt_volume = ukbiobank.utils.utils.loadCsv(ukbio=ukb, fields=['eid',
27205,
27298,
27206,
27299,
27207,
27300,
27208,
27301,
27209,
27302,
27210,
27303,
27211,
27304,
27235,
27328,
27212,
27305,
27213,
27306,
27214,
27307,
27215,
27308,
27216,
27309,
27217,
27310,
27219,
27312,
27218,
27311,
27220,
27313,
27221,
27314,
27222,
27315,
27223,
27316,
27224,
27317,
27225,
27318,
27226,
27319,
27227,
27320,
27228,
27321,
27229,
27322,
27230,
27323,
27231,
27324,
27232,
27325,
27233,
27326,
27234,
27327], instance=2)

Drop NAs, remove instance number, and save

In [ ]:
struct_dkt_volume_names = ukbiobank.utils.utils.fieldIdsToNames(ukbio=ukb, df=df_struct_dkt_volume)
struct_dkt_volume_names_nona = struct_dkt_volume_names.dropna(axis=0)
struct_dkt_volume_names_nona.columns = struct_dkt_volume_names_nona.columns.str.replace('-2.0', '')
struct_dkt_volume_names_nona.to_csv('/IBu/UK_BB/ML_DATASETS/Brain/T1/struct_dkt_volume_names_nona.csv', index=False)
struct_dkt_volume_names_nona

,Volume of superiortemporal (left hemisphere) (Field ID: 27232),Volume of parstriangularis (left hemisphere) (Field ID: 27222),Volume of parstriangularis (right hemisphere) (Field ID: 27315),Volume of superiorfrontal (left hemisphere) (Field ID: 27230),Volume of parsorbitalis (left hemisphere) (Field ID: 27221),Volume of middletemporal (right hemisphere) (Field ID: 27310),Volume of caudalmiddlefrontal (right hemisphere) (Field ID: 27299),Volume of inferiorparietal (right hemisphere) (Field ID: 27303),Volume of posteriorcingulate (left hemisphere) (Field ID: 27225),Volume of rostralanteriorcingulate (left hemisphere) (Field ID: 27228),...,Volume of caudalanteriorcingulate (left hemisphere) (Field ID: 27205),Volume of superiortemporal (right hemisphere) (Field ID: 27325),Volume of paracentral (left hemisphere) (Field ID: 27219),Volume of medialorbitofrontal (right hemisphere) (Field ID: 27309),Volume of lingual (right hemisphere) (Field ID: 27308),Volume of postcentral (left hemisphere) (Field ID: 27224),Volume of superiorparietal (left hemisphere) (Field ID: 27231),Volume of pericalcarine (left hemisphere) (Field ID: 27223),Volume of fusiform (right hemisphere) (Field ID: 27302),eid
3,16994.0,3998.0,2960.0,27910.0,2214.0,14602.0,7127.0,15627.0,4306.0,4392.0,...,4264.0,18038.0,5427.0,5477.0,7067.0,12936.0,13116.0,2758.0,9241.0,1000046
4,14302.0,4394.0,3243.0,26946.0,2076.0,11473.0,7616.0,11216.0,3300.0,4074.0,...,3219.0,12120.0,4774.0,4523.0,5954.0,10670.0,6918.0,2013.0,8933.0,1000054
15,15906.0,4589.0,5498.0,25196.0,2217.0,13272.0,5777.0,15657.0,3850.0,4044.0,...,3249.0,16602.0,4808.0,4852.0,8086.0,10856.0,9496.0,2119.0,7741.0,1000164
19,16491.0,4552.0,4516.0,27152.0,1983.0,12066.0,6719.0,14584.0,3496.0,3508.0,...,3366.0,16851.0,4869.0,4998.0,5955.0,11390.0,10533.0,1832.0,8840.0,1000203
29,20483.0,5102.0,5627.0,30531.0,2511.0,19753.0,7904.0,18189.0,4528.0,5854.0,...,4804.0,19914.0,5938.0,6346.0,9476.0,14503.0,13349.0,3344.0,11188.0,1000304
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
502304,14630.0,3849.0,3720.0,23169.0,1860.0,12434.0,5085.0,12024.0,3062.0,2909.0,...,2691.0,14928.0,4582.0,4539.0,6188.0,10448.0,11080.0,1619.0,9190.0,6024277
502311,14113.0,4235.0,3575.0,24892.0,2163.0,14840.0,7722.0,15691.0,3289.0,3431.0,...,3096.0,15341.0,4047.0,5080.0,7214.0,12031.0,11256.0,2178.0,8421.0,6024345
502335,14827.0,3876.0,4137.0,23532.0,1947.0,15187.0,6619.0,15668.0,3016.0,3666.0,...,2862.0,15517.0,4124.0,4038.0,6586.0,10258.0,9658.0,2426.0,8414.0,6024581
502337,14331.0,3868.0,3725.0,20450.0,1726.0,13925.0,4631.0,14092.0,3431.0,3181.0,...,2319.0,13519.0,3882.0,4410.0,5790.0,9643.0,9184.0,1691.0,7647.0,6024606
502338,18160.0,5094.0,4625.0,25705.0,1993.0,13952.0,5571.0,15499.0,3992.0,3825.0,...,3428.0,19872.0,4611.0,5708.0,7864.0,10612.0,9671.0,2386.0,9113.0,6024614

### 7. Freesurfer desikan gw: 70

In [26]:
df_struct_desikan_gw = ukbiobank.utils.utils.loadCsv(ukbio=ukb, fields=['eid',
26990,
27025,
26991,
27026,
26992,
27027,
26993,
27028,
26994,
27029,
27020,
27055,
26995,
27030,
26996,
27031,
26997,
27032,
27023,
27058,
26998,
27033,
26999,
27034,
27000,
27035,
27001,
27036,
27002,
27037,
27003,
27038,
27005,
27040,
27004,
27039,
27006,
27041,
27007,
27042,
27008,
27043,
27009,
27044,
27010,
27045,
27011,
27046,
27012,
27047,
27013,
27048,
27014,
27049,
27015,
27050,
27016,
27051,
27017,
27052,
27018,
27053,
27019,
27054,
27021,
27056,
27022,
27057,
26989,
27024], instance=2)

Drop NAs, remove instance number, and save

In [ ]:
struct_desikan_gw_names = ukbiobank.utils.utils.fieldIdsToNames(ukbio=ukb, df=df_struct_desikan_gw)
struct_desikan_gw_names_nona = struct_desikan_gw_names.dropna(axis=0)
struct_desikan_gw_names_nona.columns = struct_desikan_gw_names_nona.columns.str.replace('-2.0', '')
struct_desikan_gw_names_nona.to_csv('/IBu/UK_BB/ML_DATASETS/Brain/T1/struct_desikan_gw_names_nona.csv', index=False)
struct_desikan_gw_names_nona

,Grey-white contrast in precentral (right hemisphere),Grey-white contrast in insula (left hemisphere),Grey-white contrast in bankssts (right hemisphere),Grey-white contrast in caudalanteriorcingulate (left hemisphere),Grey-white contrast in temporalpole (left hemisphere),Grey-white contrast in parsorbitalis (right hemisphere),Grey-white contrast in supramarginal (left hemisphere),Grey-white contrast in unknown (left hemisphere),Grey-white contrast in isthmuscingulate (left hemisphere),Grey-white contrast in medialorbitofrontal (left hemisphere),...,Grey-white contrast in transversetemporal (left hemisphere),Grey-white contrast in cuneus (right hemisphere),Grey-white contrast in rostralmiddlefrontal (left hemisphere),Grey-white contrast in precuneus (right hemisphere),Grey-white contrast in inferiortemporal (right hemisphere),Grey-white contrast in paracentral (right hemisphere),Grey-white contrast in supramarginal (right hemisphere),Grey-white contrast in fusiform (right hemisphere),Grey-white contrast in lingual (right hemisphere),eid
3,19.0474,25.1279,26.8213,29.8647,28.5704,28.6970,28.5764,0.0122,25.3896,26.3565,...,18.7675,20.6751,28.7142,26.6806,29.1799,19.8876,26.8902,24.8773,20.6146,1000046
4,21.9100,24.2863,30.1475,29.8180,36.6876,29.2698,30.1118,0.1758,24.5351,30.1422,...,18.6838,22.1064,29.0923,26.2235,30.1819,22.8943,28.6946,28.1732,22.7808,1000054
15,21.4913,23.8410,28.5266,26.1722,28.0073,28.7145,27.8296,0.0435,25.3323,26.7487,...,17.5294,21.9419,28.3295,25.1350,29.6703,21.5378,27.3543,27.7995,22.4829,1000164
19,20.4338,24.5328,30.7952,30.4909,28.6013,30.5983,29.9905,0.1154,26.7715,28.3880,...,17.8851,21.9590,29.6336,26.2924,29.6682,21.6156,28.7400,28.4716,21.8219,1000203
29,20.1558,23.7485,27.2449,32.2450,25.1347,26.0474,26.4160,0.0503,23.0805,28.6937,...,19.8708,22.9864,24.1088,24.9850,28.9585,20.5786,26.5411,26.2171,22.2490,1000304
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
502304,20.2655,25.3873,30.3186,28.3083,29.2708,29.9668,26.7747,0.0685,22.9848,27.0546,...,18.5894,21.0351,28.8891,25.8809,28.2815,22.3623,26.2280,26.9239,21.7602,6024277
502311,20.8137,22.1955,30.5605,27.1097,31.2779,28.3772,29.3792,0.0953,24.7772,30.6023,...,21.1723,23.7691,28.8437,26.8316,29.9900,20.4923,27.5852,28.2020,23.1337,6024345
502335,20.5966,21.7884,31.3849,27.7559,29.5731,28.3667,28.2194,0.0900,23.9592,30.3584,...,20.2665,21.9022,28.6880,26.6428,29.4283,20.3517,27.4040,27.0086,21.9327,6024581
502337,19.4053,20.0390,26.6826,26.9216,26.4523,26.2180,27.4143,0.0374,23.9785,25.4226,...,18.1712,21.8357,25.3488,24.9838,27.6756,19.4521,25.1060,25.0033,20.8096,6024606
502338,22.5072,25.4031,31.4461,28.0131,29.7735,28.4646,30.6405,0.1189,27.7726,27.2482,...,22.9450,25.6467,27.1818,27.2768,31.4959,21.4525,28.1201,30.2562,25.3201,6024614

### 8. Freesurfer desikan pial: 66

In [29]:
df_desikan_pial = ukbiobank.utils.utils.loadCsv(ukbio=ukb, fields=['eid',
26923,
26956,
26924,
26957,
26925,
26958,
26926,
26959,
26927,
26960,
26928,
26961,
26954,
26987,
26929,
26962,
26930,
26963,
26931,
26964,
26932,
26965,
26933,
26966,
26934,
26967,
26935,
26968,
26936,
26969,
26937,
26970,
26939,
26972,
26938,
26971,
26940,
26973,
26941,
26974,
26942,
26975,
26943,
26976,
26944,
26977,
26945,
26978,
26946,
26979,
26947,
26980,
26948,
26981,
26949,
26982,
26950,
26983,
26951,
26984,
26952,
26985,
26953,
26986,
26955,
26988], instance=2)

Drop NAs, remove instance number, and save

In [ ]:
struct_desikan_pial_names = ukbiobank.utils.utils.fieldIdsToNames(ukbio=ukb, df=df_desikan_pial)
struct_desikan_pial_names_nona = struct_desikan_pial_names.dropna(axis=0)
struct_desikan_pial_names_nona.columns = struct_desikan_pial_names_nona.columns.str.replace('-2.0', '')
struct_desikan_pial_names_nona.to_csv('/IBu/UK_BB/ML_DATASETS/Brain/T1/struct_desikan_pial_names_nona.csv', index=False)
struct_desikan_pial_names_nona

,Area of frontalpole (left hemisphere) (Field ID: 26954),Area of bankssts (right hemisphere) (Field ID: 26957),Area of parstriangularis (left hemisphere) (Field ID: 26942),Area of entorhinal (left hemisphere) (Field ID: 26928),Area of superiorparietal (left hemisphere) (Field ID: 26951),Area of TotalSurface (left hemisphere) (Field ID: 26923),Area of postcentral (right hemisphere) (Field ID: 26977),Area of middletemporal (right hemisphere) (Field ID: 26970),Area of inferiortemporal (left hemisphere) (Field ID: 26931),Area of supramarginal (right hemisphere) (Field ID: 26986),...,Area of caudalmiddlefrontal (right hemisphere) (Field ID: 26959),Area of paracentral (left hemisphere) (Field ID: 26939),Area of rostralmiddlefrontal (left hemisphere) (Field ID: 26949),Area of frontalpole (right hemisphere) (Field ID: 26987),Area of superiorparietal (right hemisphere) (Field ID: 26984),Area of parsorbitalis (left hemisphere) (Field ID: 26941),Area of superiortemporal (right hemisphere) (Field ID: 26985),Area of TotalSurface (right hemisphere) (Field ID: 26956),Area of lingual (left hemisphere) (Field ID: 26935),eid
3,432.0,946.0,1404.0,613.0,6618.0,105401.0,5144.0,4576.0,5293.0,4833.0,...,2619.0,1735.0,6942.0,511.0,6981.0,1068.0,4625.0,104893.0,3930.0,1000046
4,422.0,754.0,1470.0,1057.0,3950.0,92678.2,3757.0,4363.0,3536.0,2837.0,...,2833.0,1646.0,5841.0,375.0,4219.0,1008.0,3569.0,92680.0,3450.0,1000054
15,389.0,663.0,1430.0,812.0,5295.0,95829.0,4250.0,4214.0,4523.0,3656.0,...,2035.0,1565.0,5894.0,489.0,5012.0,1037.0,4413.0,96785.9,3409.0,1000164
19,400.0,797.0,1587.0,841.0,5671.0,97825.1,4267.0,3971.0,3924.0,4025.0,...,2419.0,1686.0,7126.0,545.0,6124.0,1066.0,4766.0,98065.1,3673.0,1000203
29,488.0,921.0,1652.0,900.0,7315.0,124395.0,5486.0,6211.0,5425.0,4281.0,...,2760.0,1920.0,8666.0,630.0,8063.0,1150.0,5237.0,124999.0,4895.0,1000304
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
502304,314.0,659.0,1296.0,702.0,5847.0,87039.1,4146.0,4032.0,4620.0,3903.0,...,1824.0,1578.0,5100.0,406.0,6142.0,794.0,3793.0,88959.1,2822.0,6024277
502311,443.0,814.0,1390.0,795.0,6625.0,98375.5,4807.0,4625.0,4638.0,4428.0,...,2885.0,1474.0,6789.0,575.0,6898.0,1061.0,3894.0,99571.0,3884.0,6024345
502335,373.0,882.0,1521.0,643.0,5634.0,98719.0,4803.0,5120.0,4764.0,4331.0,...,2413.0,1478.0,5922.0,507.0,5837.0,728.0,4178.0,99717.2,3570.0,6024581
502337,371.0,671.0,1227.0,602.0,5736.0,91318.9,4406.0,4948.0,4238.0,3522.0,...,1717.0,1526.0,5384.0,390.0,5757.0,704.0,4103.0,90467.6,3195.0,6024606
502338,413.0,793.0,1502.0,786.0,5439.0,97648.4,4583.0,4300.0,4790.0,3189.0,...,2098.0,1630.0,6736.0,529.0,5010.0,891.0,5221.0,96318.0,3588.0,6024614

### 9. Freesurfer desikan white

#### 9.1 Freesurfer desikan white Area: 68

In [32]:
df_struct_desikan_white_area = ukbiobank.utils.utils.loadCsv(ukbio=ukb, fields=['eid',
26721,
26822,
26722,
26823,
26723,
26824,
26724,
26825,
26725,
26826,
26726,
26827,
26752,
26853,
26727,
26828,
26728,
26829,
26729,
26830,
26754,
26855,
26730,
26831,
26731,
26832,
26732,
26833,
26733,
26834,
26734,
26835,
26735,
26836,
26737,
26838,
26736,
26837,
26738,
26839,
26739,
26840,
26740,
26841,
26741,
26842,
26742,
26843,
26743,
26844,
26744,
26845,
26745,
26846,
26746,
26847,
26747,
26848,
26748,
26849,
26749,
26850,
26750,
26851,
26751,
26852,
26753,
26854], instance=2)

Drop NAs, remove instance number, and save

In [ ]:
struct_desikan_white_area_names = ukbiobank.utils.utils.fieldIdsToNames(ukbio=ukb, df=df_struct_desikan_white_area)
struct_desikan_white_area_names_nona = struct_desikan_white_area_names.dropna(axis=0)
struct_desikan_white_area_names_nona.columns = struct_desikan_white_area_names_nona.columns.str.replace('-2.0', '')
struct_desikan_white_area_names_nona.to_csv('/IBu/UK_BB/ML_DATASETS/Brain/T1/struct_desikan_white_area_names_nona.csv', index=False)
struct_desikan_white_area_names_nona

,Area of bankssts (left hemisphere) (Field ID: 26722),Area of inferiortemporal (left hemisphere) (Field ID: 26729),Area of postcentral (right hemisphere) (Field ID: 26843),Area of superiorfrontal (left hemisphere) (Field ID: 26748),Area of paracentral (right hemisphere) (Field ID: 26838),Area of fusiform (left hemisphere) (Field ID: 26727),Area of inferiorparietal (left hemisphere) (Field ID: 26728),Area of precentral (left hemisphere) (Field ID: 26744),Area of caudalmiddlefrontal (right hemisphere) (Field ID: 26825),Area of lingual (right hemisphere) (Field ID: 26834),...,Area of inferiortemporal (right hemisphere) (Field ID: 26830),Area of pericalcarine (right hemisphere) (Field ID: 26842),Area of lateraloccipital (left hemisphere) (Field ID: 26731),Area of caudalmiddlefrontal (left hemisphere) (Field ID: 26724),Area of precuneus (left hemisphere) (Field ID: 26745),Area of transversetemporal (left hemisphere) (Field ID: 26753),Area of cuneus (right hemisphere) (Field ID: 26826),Area of precentral (right hemisphere) (Field ID: 26845),Area of parstriangularis (right hemisphere) (Field ID: 26841),eid
3,879.0,3948.0,4325.0,7770.0,1523.0,3343.0,4434.0,4613.0,2324.0,3866.0,...,3267.0,1887.0,5387.0,2438.0,3787.0,485.0,1769.0,5019.0,1169.0,1000046
4,912.0,2826.0,3024.0,7539.0,1245.0,3320.0,3579.0,5597.0,2366.0,3455.0,...,3149.0,1494.0,4852.0,2675.0,2691.0,356.0,1672.0,4995.0,1268.0,1000054
15,782.0,3574.0,3641.0,7251.0,1579.0,2986.0,4267.0,4507.0,1783.0,3611.0,...,3194.0,1609.0,4761.0,1950.0,3506.0,405.0,1503.0,4591.0,1738.0,1000164
19,957.0,3085.0,3475.0,7107.0,1633.0,3349.0,3968.0,4489.0,2123.0,3254.0,...,3017.0,1601.0,4666.0,2322.0,3489.0,445.0,1938.0,4807.0,1522.0,1000203
29,1036.0,4162.0,4639.0,9935.0,1957.0,3998.0,4882.0,6129.0,2455.0,3948.0,...,4361.0,2073.0,7262.0,3736.0,4699.0,447.0,2206.0,6852.0,1995.0,1000304
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
502304,1011.0,3511.0,3455.0,6364.0,1241.0,2685.0,3911.0,4187.0,1689.0,3169.0,...,3300.0,1363.0,3956.0,1774.0,3252.0,359.0,1504.0,4295.0,1271.0,6024277
502311,1001.0,3546.0,4075.0,7577.0,1307.0,2893.0,4512.0,5105.0,2498.0,3236.0,...,3088.0,1487.0,4234.0,2330.0,3483.0,417.0,1721.0,4917.0,1318.0,6024345
502335,962.0,3762.0,3914.0,6713.0,1496.0,3410.0,4773.0,4551.0,2122.0,3381.0,...,3739.0,1945.0,4840.0,2042.0,3485.0,423.0,1626.0,4629.0,1508.0,6024581
502337,962.0,3065.0,3561.0,6246.0,1369.0,2834.0,4107.0,4141.0,1543.0,2961.0,...,3352.0,1400.0,4657.0,1619.0,3083.0,416.0,1699.0,3792.0,1340.0,6024606
502338,875.0,3394.0,3695.0,7399.0,1738.0,2753.0,3867.0,4988.0,1817.0,2960.0,...,2601.0,1272.0,5076.0,2331.0,3529.0,394.0,1334.0,4941.0,1592.0,6024614

#### 9.2 Freesurfer desikan white Mean thickness: 68

In [35]:
df_struct_desikan_white_mean_thickness = ukbiobank.utils.utils.loadCsv(ukbio=ukb, fields=['eid',
26755,
26856,
26756,
26857,
26757,
26858,
26758,
26859,
26759,
26860,
26760,
26861,
26786,
26887,
26761,
26862,
26762,
26863,
26763,
26864,
26788,
26889,
26764,
26865,
26765,
26866,
26766,
26867,
26767,
26868,
26768,
26869,
26769,
26870,
26771,
26872,
26770,
26871,
26772,
26873,
26773,
26874,
26774,
26875,
26775,
26876,
26776,
26877,
26777,
26878,
26778,
26879,
26779,
26880,
26780,
26881,
26781,
26882,
26782,
26883,
26783,
26884,
26784,
26885,
26785,
26886,
26787,
26888], instance=2)

Drop NAs, remove instance number, and save

In [ ]:
struct_desikan_white_mean_thickness_names = ukbiobank.utils.utils.fieldIdsToNames(ukbio=ukb, df=df_struct_desikan_white_mean_thickness)
struct_desikan_white_mean_thickness_names_nona = struct_desikan_white_mean_thickness_names.dropna(axis=0)
struct_desikan_white_mean_thickness_names_nona.columns = struct_desikan_white_mean_thickness_names_nona.columns.str.replace('-2.0', '')
struct_desikan_white_mean_thickness_names_nona.to_csv('/IBu/UK_BB/ML_DATASETS/Brain/T1/struct_desikan_white_mean_thickness_names_nona.csv', index=False)
struct_desikan_white_mean_thickness_names_nona

,Mean thickness of parstriangularis (left hemisphere) (Field ID: 26774),Mean thickness of transversetemporal (left hemisphere) (Field ID: 26787),Mean thickness of superiortemporal (left hemisphere) (Field ID: 26784),Mean thickness of rostralanteriorcingulate (left hemisphere) (Field ID: 26780),Mean thickness of precuneus (right hemisphere) (Field ID: 26880),Mean thickness of frontalpole (left hemisphere),Mean thickness of postcentral (left hemisphere) (Field ID: 26776),Mean thickness of superiorfrontal (right hemisphere) (Field ID: 26883),Mean thickness of parsorbitalis (right hemisphere) (Field ID: 26874),Mean thickness of fusiform (right hemisphere) (Field ID: 26862),...,Mean thickness of posteriorcingulate (left hemisphere) (Field ID: 26777),Mean thickness of middletemporal (left hemisphere) (Field ID: 26769),Mean thickness of lateralorbitofrontal (left hemisphere) (Field ID: 26766),Mean thickness of postcentral (right hemisphere) (Field ID: 26877),Mean thickness of parsopercularis (left hemisphere) (Field ID: 26772),Mean thickness of caudalanteriorcingulate (right hemisphere) (Field ID: 26858),Mean thickness of bankssts (left hemisphere),Mean thickness of parstriangularis (right hemisphere) (Field ID: 26875),Mean thickness of parsopercularis (right hemisphere) (Field ID: 26873),eid
3,2.632,2.396,3.026,3.099,2.671,2.964,2.352,2.937,2.884,2.921,...,2.662,3.109,2.846,2.272,2.958,2.663,2.752,2.665,2.849,1000046
4,2.821,2.365,2.892,2.918,2.504,2.830,2.735,2.931,2.770,2.808,...,2.766,3.016,2.639,2.687,2.971,2.892,2.818,2.588,2.807,1000054
15,2.765,2.560,2.896,3.134,2.622,2.933,2.345,3.005,3.166,2.947,...,2.595,2.739,2.752,2.363,2.727,2.625,2.447,2.736,2.700,1000164
19,2.801,2.630,2.887,3.052,2.764,2.855,2.426,3.049,2.845,2.843,...,2.409,2.982,2.854,2.391,2.964,2.546,2.927,2.757,3.019,1000203
29,2.501,2.852,3.037,3.059,2.713,2.961,2.383,2.964,2.961,2.926,...,2.873,2.938,3.028,2.411,2.795,2.928,2.536,2.636,3.044,1000304
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
502304,2.702,2.606,2.950,3.109,2.773,2.960,2.374,3.059,3.021,3.032,...,2.789,2.924,2.778,2.319,2.881,2.807,3.052,2.689,2.849,6024277
502311,2.508,2.303,2.817,2.631,2.476,2.805,2.096,3.028,3.021,3.026,...,2.458,2.879,2.805,2.294,2.602,2.855,2.618,2.511,2.610,6024345
502335,2.559,2.069,2.741,2.948,2.601,2.528,1.973,2.947,2.815,2.699,...,2.519,2.678,2.726,2.178,2.509,1.902,2.792,2.642,2.746,6024581
502337,2.708,2.488,2.515,2.901,2.512,2.495,2.061,2.718,2.763,2.824,...,2.597,2.823,2.867,2.055,2.653,2.115,2.520,2.547,2.564,6024606
502338,3.110,2.943,3.091,3.022,2.606,2.618,2.353,3.016,3.171,3.233,...,2.544,3.035,3.156,2.399,3.015,2.687,2.696,2.822,3.101,6024614

#### 9.3 Freesurfer desikan white Volume: 66

In [41]:
df_struct_desikan_white_volume = ukbiobank.utils.utils.loadCsv(ukbio=ukb, fields=['eid',
26789,
26890,
26790,
26891,
26791,
26892,
26792,
26893,
26793,
26894,
26819,
26920,
26794,
26895,
26795,
26896,
26796,
26897,
26821,
26922,
26797,
26898,
26798,
26899,
26799,
26900,
26800,
26901,
26801,
26902,
26802,
26903,
26804,
26905,
26803,
26904,
26805,
26906,
26806,
26907,
26807,
26908,
26808,
26909,
26809,
26910,
26810,
26911,
26811,
26912,
26812,
26913,
26813,
26914,
26814,
26915,
26815,
26916,
26816,
26917,
26817,
26918,
26818,
26919,
26820,
26921], instance=2)

Drop NAs, remove instance number, and save

In [ ]:
struct_desikan_white_volume_names = ukbiobank.utils.utils.fieldIdsToNames(ukbio=ukb, df=df_struct_desikan_white_volume)
struct_desikan_white_volume_names_nona = struct_desikan_white_volume_names.dropna(axis=0)
struct_desikan_white_volume_names_nona.columns = struct_desikan_white_volume_names_nona.columns.str.replace('-2.0', '')
struct_desikan_white_volume_names_nona.to_csv('/IBu/UK_BB/ML_DATASETS/Brain/T1/struct_desikan_white_volume_names_nona.csv', index=False)
struct_desikan_white_volume_names_nona

,Volume of parahippocampal (right hemisphere) (Field ID: 26904),Volume of medialorbitofrontal (right hemisphere) (Field ID: 26902),Volume of inferiorparietal (right hemisphere) (Field ID: 26896),Volume of cuneus (right hemisphere) (Field ID: 26893),Volume of inferiortemporal (left hemisphere) (Field ID: 26796),Volume of parsorbitalis (right hemisphere) (Field ID: 26907),Volume of middletemporal (right hemisphere) (Field ID: 26903),Volume of pericalcarine (right hemisphere) (Field ID: 26909),Volume of caudalanteriorcingulate (right hemisphere) (Field ID: 26891),Volume of insula (right hemisphere) (Field ID: 26922),...,Volume of transversetemporal (right hemisphere) (Field ID: 26921),Volume of superiorparietal (right hemisphere) (Field ID: 26917),Volume of paracentral (right hemisphere) (Field ID: 26905),Volume of bankssts (left hemisphere),Volume of entorhinal (left hemisphere) (Field ID: 26793),Volume of rostralmiddlefrontal (right hemisphere) (Field ID: 26915),Volume of parsopercularis (left hemisphere) (Field ID: 26805),Volume of superiorfrontal (right hemisphere) (Field ID: 26916),Volume of superiortemporal (left hemisphere) (Field ID: 26817),eid
3,2074.0,6397.0,15332.0,3874.0,13794.0,3214.0,12899.0,3332.0,2711.0,8104.0,...,900.0,16245.0,4114.0,2343.0,1554.0,20455.0,5820.0,23982.0,12563.0,1000046
4,1544.0,5960.0,11132.0,2697.0,9442.0,2860.0,9608.0,2075.0,1423.0,6616.0,...,842.0,9556.0,3701.0,2411.0,2316.0,14838.0,6254.0,24836.0,10577.0,1000054
15,2070.0,5538.0,15900.0,3310.0,11583.0,3215.0,11343.0,2627.0,2239.0,7819.0,...,1014.0,11998.0,4864.0,1789.0,2196.0,16299.0,4666.0,23029.0,11806.0,1000164
19,2036.0,6212.0,14589.0,3444.0,10438.0,2607.0,10281.0,2019.0,2443.0,7033.0,...,1199.0,14109.0,4372.0,2576.0,2343.0,18951.0,4849.0,20725.0,12337.0,1000203
29,2426.0,8097.0,18606.0,4497.0,15592.0,3299.0,17603.0,3727.0,4775.0,8303.0,...,1179.0,17928.0,5212.0,2461.0,2362.0,18633.0,4236.0,26851.0,15788.0,1000304
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
502304,2267.0,5356.0,12422.0,3012.0,11973.0,2569.0,10767.0,2174.0,1876.0,6802.0,...,1006.0,14483.0,3722.0,2804.0,1844.0,14977.0,4433.0,19910.0,10780.0,6024277
502311,2095.0,6177.0,15552.0,3136.0,12225.0,2992.0,12860.0,2105.0,2348.0,6547.0,...,705.0,14960.0,3723.0,2378.0,1962.0,16874.0,4037.0,22527.0,10588.0,6024345
502335,1666.0,5565.0,15937.0,2705.0,12095.0,2320.0,13060.0,2984.0,1150.0,6620.0,...,744.0,12563.0,3880.0,2607.0,1653.0,14421.0,4454.0,22968.0,10987.0,6024581
502337,1810.0,5859.0,14439.0,3258.0,10838.0,2410.0,12152.0,1877.0,1668.0,5970.0,...,953.0,11928.0,3376.0,2220.0,1562.0,13012.0,3489.0,17886.0,10638.0,6024606
502338,2304.0,6667.0,15852.0,3423.0,12891.0,3020.0,11974.0,2457.0,2862.0,8316.0,...,944.0,11432.0,4846.0,2294.0,2348.0,16348.0,4779.0,24981.0,13574.0,6024614

### 10. Freesurfer subsegmentation: 121

In [42]:
df_struct_subsegmentation = ukbiobank.utils.utils.loadCsv(ukbio=ukb, fields=['eid',
26684,
26710,
26602,
26612,
26603,
26613,
26601,
26611,
26622,
26644,
26626,
26648,
26632,
26654,
26637,
26659,
26635,
26657,
26634,
26656,
26681,
26706,
26670,
26694,
26677,
26703,
26604,
26614,
26606,
26616,
26607,
26617,
26633,
26655,
26631,
26653,
26638,
26660,
26620,
26642,
26668,
26692,
26712,
26713,
26665,
26688,
26687,
26711,
26600,
26610,
26676,
26700,
26673,
26697,
26664,
26689,
26679,
26702,
26605,
26615,
26716,
26719,
26608,
26618,
26685,
26708,
26674,
26698,
26717,
26683,
26709,
26672,
26696,
26666,
26690,
26682,
26705,
26667,
26691,
26718,
26678,
26701,
26675,
26699,
26671,
26695,
26686,
26707,
26680,
26704,
26669,
26693,
26609,
26619,
26720,
26639,
26661,
26640,
26662,
26641,
26663,
26714,
26715,
26636,
26658,
26624,
26646,
26630,
26652,
26629,
26651,
26628,
26650,
26627,
26649,
26625,
26647,
26621,
26643,
26623,
26645], instance=2)

Drop NAs, remove instance number, and save

In [ ]:
struct_subsegmentation_names = ukbiobank.utils.utils.fieldIdsToNames(ukbio=ukb, df=df_struct_subsegmentation)
struct_subsegmentation_names_nona = struct_subsegmentation_names.dropna(axis=0)
struct_subsegmentation_names_nona.columns = struct_subsegmentation_names_nona.columns.str.replace('-2.0', '')
struct_subsegmentation_names_nona.to_csv('/IBu/UK_BB/ML_DATASETS/Brain/T1/struct_subsegmentation_names_nona.csv', index=False)
struct_subsegmentation_names_nona

,Volume of Corticoamygdaloid-transitio (left hemisphere),Volume of CA4-head (left hemisphere),Volume of CA3-head (right hemisphere),Volume of Lateral-nucleus (left hemisphere),Volume of Whole-hippocampal-head (right hemisphere),Volume of subiculum-body (left hemisphere),Volume of LP (right hemisphere),Volume of subiculum-head (right hemisphere),Volume of CM (left hemisphere),Volume of GC-ML-DG-head (right hemisphere),...,Volume of Central-nucleus (right hemisphere),Volume of CA1-head (left hemisphere),Volume of CA1-body (right hemisphere),Volume of Pt (left hemisphere),Volume of GC-ML-DG-body (right hemisphere),Volume of AV (left hemisphere),Volume of Medial-nucleus (right hemisphere),Volume of SCP (whole brain),Volume of CA3-body (right hemisphere),eid
3,186.167,135.333,175.893,644.256,1869.80,286.060,122.3320,204.860,276.166,188.106,...,56.0402,543.069,139.019,7.39741,181.303,114.5850,31.1835,234.888,125.923,1000046
4,170.075,136.727,140.928,588.441,1569.92,269.809,90.1153,167.677,176.705,150.909,...,48.5784,546.068,166.704,4.34077,155.459,103.3270,27.8365,193.395,116.620,1000054
15,162.972,148.960,131.742,669.935,1876.42,260.128,89.6782,246.518,224.527,179.639,...,38.7274,572.716,184.064,5.93119,178.580,123.7750,20.0141,304.535,137.423,1000164
19,167.971,155.377,156.511,683.038,2030.48,301.586,127.7870,238.387,234.551,180.125,...,72.1942,643.915,151.775,6.19890,186.380,118.7390,24.9242,227.427,118.591,1000203
29,183.669,144.649,178.579,731.835,1924.77,265.899,132.3030,185.601,246.762,210.690,...,63.1400,542.595,227.594,7.38264,189.962,157.3490,36.4908,314.910,167.732,1000304
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
502304,175.197,118.806,153.970,581.209,1872.93,331.141,119.9410,204.523,215.155,181.525,...,47.5122,511.204,154.270,5.55104,163.275,91.0076,20.0751,244.136,124.939,6024277
502311,161.779,144.814,168.559,636.527,1993.44,281.626,105.5450,233.364,208.759,183.302,...,51.9625,565.545,177.153,6.16816,179.978,114.9570,15.2309,269.319,137.573,6024345
502335,194.660,133.953,182.079,705.579,1926.60,287.888,114.1210,199.728,247.141,192.419,...,56.5110,608.382,177.471,6.89137,171.725,115.1450,28.9342,274.578,135.218,6024581
502337,137.179,124.196,169.620,558.771,1704.47,260.427,75.1673,150.753,240.870,190.245,...,57.6713,492.291,142.358,6.42474,161.946,95.9906,25.6430,297.059,119.441,6024606
502338,215.447,182.695,196.157,747.533,2043.87,282.157,107.2840,196.818,222.653,200.958,...,75.1983,667.572,172.739,7.06858,187.851,142.8580,28.3291,310.549,159.049,6024614

### 11. Additional: T1 and T2

### T1 

- 25010	Volume of brain, grey+white matter
- 25009	Volume of brain, grey+white matter (normalised for head size) - exclude
- 25008	Volume of white matter
- 25007	Volume of white matter (normalised for head size) - exclude
- 25006	Volume of grey matter
- 25005	Volume of grey matter (normalised for head size) - exclude
- 25002	Volume of peripheral cortical grey matter
- 25001	Volume of peripheral cortical grey matter (normalised for head size) - exclude
- 25004	Volume of ventricular cerebrospinal fluid
- 25003	Volume of ventricular cerebrospinal fluid (normalised for head size) - exclude
- 25025	Volume of brain stem + 4th ventricle
- 26536	Volume-ratio of BrainSegVol-to-eTIV (whole brain)
- 26537	Volume-ratio of MaskVol-to-eTIV (whole brain)

Exclude:

- 26568	Number of HolesBeforeFixing (left hemisphere)
- 26599	Number of HolesBeforeFixing (right hemisphere)

In [5]:
df_add_t1 = ukbiobank.utils.utils.loadCsv(ukbio=ukb, fields=['eid',
25010, #Volume of brain, grey+white matter - T1
#25009, Volume of brain, grey+white matter (normalised for head size) - T1
25008, #Volume of white matter - T1
#25007, Volume of white matter (normalised for head size) - T1
25006, #Volume of grey matter - T1
#25005, Volume of grey matter (normalised for head size) - T1
25002, #Volume of peripheral cortical grey matter - T1
#25001, Volume of peripheral cortical grey matter (normalised for head size) - T1
25004, #Volume of ventricular cerebrospinal fluid - T1
#25003, Volume of ventricular cerebrospinal fluid (normalised for head size)  - T1
25025, #Volume of brain stem + 4th ventricle - T1
26536, #Volume-ratio of BrainSegVol-to-eTIV (whole brain) - T1
26537, #Volume-ratio of MaskVol-to-eTIV (whole brain) - T1
], instance=2)

In [ ]:
add_t1_names = ukbiobank.utils.utils.fieldIdsToNames(ukbio=ukb, df=df_add_t1)
add_t1_names_nona = add_t1_names.dropna(axis=0)
add_t1_names_nona.columns = add_t1_names_nona.columns.str.replace('-2.0', '')
add_t1_names_nona.to_csv('/IBu/UK_BB/ML_DATASETS/Brain/T1/additional_(t1-t2-MRI)-T1_names_nona.csv', index=False)
add_t1_names_nona

,Volume of grey matter,Volume of brain stem + 4th ventricle,Volume of ventricular cerebrospinal fluid,Volume of white matter,Volume-ratio of MaskVol-to-eTIV (whole brain),Volume-ratio of BrainSegVol-to-eTIV (whole brain),"Volume of brain, grey+white matter",Volume of peripheral cortical grey matter,eid
3,639441.0,24497.0,41888.2,625897.0,1.05405,0.783390,1265340.0,512167.0,1000046
4,554252.0,19012.0,24449.0,485921.0,1.03431,0.775019,1040170.0,433015.0,1000054
15,580833.0,22899.0,38005.6,522046.0,1.01186,0.784604,1102880.0,451502.0,1000164
19,594616.0,25075.0,25063.4,559692.0,1.04755,0.798140,1154310.0,463864.0,1000203
29,739652.0,22876.0,46465.8,645728.0,1.09124,0.860159,1385380.0,591659.0,1000304
...,...,...,...,...,...,...,...,...,...
502304,559894.0,22690.0,26015.2,489085.0,1.01020,0.792404,1048980.0,434513.0,6024277
502311,588574.0,18643.0,21133.9,510778.0,1.01895,0.781388,1099350.0,469744.0,6024345
502335,646878.0,25153.0,29826.7,555026.0,1.05487,0.748471,1201900.0,500626.0,6024581
502337,548174.0,21373.0,40969.9,457485.0,1.00951,0.729550,1005660.0,433411.0,6024606
502338,599598.0,21152.0,64236.8,539510.0,1.03650,0.718221,1139110.0,463480.0,6024614

# Confounds

## Upload confoudns

### T1w additional

Basic

- 25925	Intensity scaling for T1
- 26500	T2-FLAIR used (in addition to T1) to run FreeSurfer
- 25733	Amount of warping applied to non-linearly align T1 brain image to standard-space
- 25731	Discrepancy between T1 brain image and standard-space brain template (linearly-aligned)
- 25732	Discrepancy between T1 brain image and standard-space brain template (nonlinearly-aligned)
- 25735	Inverted contrast-to-noise ratio in T1
- 25734	Inverted signal-to-noise ratio in T1
- 25000	Volumetric scaling from T1 head image to standard space
- 25756	Scanner lateral (X) brain position
- 25757	Scanner transverse (Y) brain position
- 25758	Scanner longitudinal (Z) brain position
- 25759	Scanner table position

### Confounds from other MRI modalities

- Head size: 25000
- Site: 54
- Acquisition date: 53
- STRUCT MOTION: 24419
- Discrepancy between T1 brain image and standard-space brain template (linearly-aligned): 25731
- Discrepancy between T1 brain image and standard-space brain template (nonlinearly-aligned): 25732

In [ ]:
df_add_t1_conf = ukbiobank.utils.utils.loadCsv(ukbio=ukb, fields=['eid',
], instance=2)
add_t1_conf_names = ukbiobank.utils.utils.fieldIdsToNames(ukbio=ukb, df=df_add_t1_conf)
add_t1_conf_names_nona = add_t1_conf_names.dropna(axis=0)
add_t1_conf_names_nona.columns = add_t1_conf_names_nona.columns.str.replace('-2.0', '')
add_t1_conf_names_nona.to_csv('/IBu/UK_BB/ML_DATASETS/Brain/T1/additional_(t1-t2-MRI)-T1_CONF.csv', index=False)
add_t1_conf_names_nona

### T2w

- 24486	Total volume of deep white matter hyperintensities
- 24485	Total volume of peri-ventricular white matter hyperintensities
- 25781	Total volume of white matter hyperintensities (from T1 and T2_FLAIR images)

#### Confound:

- 25926	Intensity scaling for T2_FLAIR
- 25736	Discrepancy between T2 FLAIR brain image and T1 brain image

In [ ]:
df_add_t2 = ukbiobank.utils.utils.loadCsv(ukbio=ukb, fields=['eid',
24486,	#Total volume of deep white matter hyperintensities - T2
24485,	#Total volume of peri-ventricular white matter hyperintensities - T2
25781,	#Total volume of white matter hyperintensities (from T1 and T2_FLAIR images) - T2
], instance=2)
add_t2_names = ukbiobank.utils.utils.fieldIdsToNames(ukbio=ukb, df=df_add_t2)
add_t2_names_nona = add_t2_names.dropna(axis=0)
add_t2_names_nona.columns = add_t2_names_nona.columns.str.replace('-2.0', '')
add_t2_names_nona.to_csv('/IBu/UK_BB/ML_DATASETS/Brain/T1/additional_(t1-t2-MRI)-T2_names_nona.csv', index=False)
add_t2_names_nona

If you want to upload particular columns from a big csv, use 'usecols=[]'

In [ ]:
add_t2 = pd.read_csv('/IBu/UK_BB/ukbbdata/ukbb_oct23/ukb675684.csv', usecols=['eid','24486-2.0', '24485-2.0', '25781-2.0'])
add_t2.columns = ['eid','Total volume of deep white matter hyperintensities from T2', 'Total volume of peri-ventricular white matter hyperintensities from T2', 'Total volume of white matter hyperintensities (from T1 and T2_FLAIR images)']
add_t2_nona = add_t2.dropna(axis=0).reset_index(drop=True)
add_t2_nona.to_csv('/IBu/UK_BB/ML_DATASETS/Brain/T1/additional_(t1-t2-MRI)-T2_names_nona.csv', index=False)

Upload confounds for T2

- Head size: 25000
- Site: 54
- Acquisition date: 53
- STRUCT MOTION: 24419
- Discrepancy between T1 brain image and standard-space brain template (linearly-aligned): 25731
- Discrepancy between T1 brain image and standard-space brain template (nonlinearly-aligned): 25732

In [ ]:
df_add_t2_conf = ukbiobank.utils.utils.loadCsv(ukbio=ukb, fields=['eid',
25926,
25736,
25000,
54,
53,
24419], instance=2)
add_t2_conf_names = ukbiobank.utils.utils.fieldIdsToNames(ukbio=ukb, df=df_add_t2_conf)
add_t2_conf_names_nona = add_t2_conf_names.dropna(axis=0)
add_t2_conf_names_nona.columns = add_t2_conf_names_nona.columns.str.replace('-2.0', '')
add_t2_conf_names_nona.to_csv('/IBu/UK_BB/ML_DATASETS/Brain/T1/additional_(t1-t2-MRI)-T2_CONF_RAW.csv', index=False)
add_t2_conf_names_nona

The following variables were not found:
 [24419].

 This may be because the same fieldname is used across multiple field IDs.

 Either check the spelling of the variables or alternatively try using the field ID

/home/irinabu/anaconda3/envs/ukbiobank_py11/lib/python3.11/site-packages/ukbiobank/utils/utils.py:296: DtypeWarning: Columns (98,99,100) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(ukbio.csv_path, usecols=new_fields)

,Intensity scaling for T2_FLAIR,Date of attending assessment centre,UK Biobank assessment centre,Volumetric scaling from T1 head image to standard space,Discrepancy between T2 FLAIR brain image and T1 brain image,eid
3,6.0,2015-07-24,11025.0,1.25540,0.326541,1000046
4,6.0,2019-11-19,11025.0,1.43688,0.435115,1000054
15,6.0,2018-10-14,11025.0,1.34341,0.352936,1000164
19,6.0,2017-11-15,11025.0,1.32704,0.371938,1000203
29,6.0,2017-12-17,11025.0,1.10518,0.417996,1000304
...,...,...,...,...,...,...
502304,6.0,2022-03-18,11025.0,1.51751,0.339303,6024277
502311,6.0,2015-02-25,11025.0,1.35167,0.403931,6024345
502335,6.0,2017-06-07,11025.0,1.31166,0.352528,6024581
502337,5.0,2016-03-13,11025.0,1.38344,0.275130,6024606
502338,6.0,2019-11-23,11025.0,1.22325,0.316414,6024614

In [ ]:
add_t2_conf = pd.read_csv('/IBu/UK_BB/ukbbdata/ukbb_oct23/ukb675684.csv', usecols=['eid', '24419-2.0'])
add_t2_conf.columns = ['eid', 'Struct.motion']
add_t2_conf_nona = add_t2_conf.dropna(axis=0).reset_index(drop=True)
add_t2_conf_full = pd.merge(add_t2_conf_names_nona, add_t2_conf_nona, on='eid')
add_t2_conf_full = pd.merge(add_t2_conf_names_nona, add_t2_conf_nona, on='eid')
add_t2_conf_full.to_csv('/IBu/UK_BB/ML_DATASETS/Brain/T1/additional_(t1-t2-MRI)-T2_CONF_RAW_FULL.csv', index=False)
add_t2_conf_full

,Intensity scaling for T2_FLAIR,Date of attending assessment centre,UK Biobank assessment centre,Volumetric scaling from T1 head image to standard space,Discrepancy between T2 FLAIR brain image and T1 brain image,eid,Struct.motion
0,6.0,2015-07-24,11025.0,1.25540,0.326541,1000046,0.166306
1,6.0,2019-11-19,11025.0,1.43688,0.435115,1000054,0.488937
2,6.0,2018-10-14,11025.0,1.34341,0.352936,1000164,0.321029
3,6.0,2017-11-15,11025.0,1.32704,0.371938,1000203,0.299027
4,6.0,2017-12-17,11025.0,1.10518,0.417996,1000304,0.342515
...,...,...,...,...,...,...,...
44996,6.0,2022-03-18,11025.0,1.51751,0.339303,6024277,0.196698
44997,6.0,2015-02-25,11025.0,1.35167,0.403931,6024345,0.448581
44998,6.0,2017-06-07,11025.0,1.31166,0.352528,6024581,0.246757
44999,5.0,2016-03-13,11025.0,1.38344,0.275130,6024606,0.117782
45000,6.0,2019-11-23,11025.0,1.22325,0.316414,6024614,0.379711

Convert date to Unix & site to Dummy

In [ ]:
# Convert date
import datetime
add_t2_conf_full = pd.read_csv('/IBu/UK_BB/ML_DATASETS/Brain/T1/additional_(t1-t2-MRI)-T2_CONF_RAW_FULL.csv')
add_t2_conf_unix = add_t2_conf_full.copy()
add_t2_conf_unix['Date of attending assessment centre'] = pd.to_datetime(add_t2_conf_unix['Date of attending assessment centre'], format="%Y-%m-%d")  #"%m/%d/%Y")
add_t2_conf_unix['Date of attending assessment centre'] = add_t2_conf_unix['Date of attending assessment centre'].apply(datetime.datetime.timestamp)

# Round values
add_t2_conf_unix['Date of attending assessment centre'] = add_t2_conf_unix['Date of attending assessment centre'].apply(int)
print(add_t2_conf_unix['Date of attending assessment centre'])

# Dummy encode site
add_t2_conf_unix_dummy = pd.get_dummies(add_t2_conf_unix, columns=['UK Biobank assessment centre'], dtype=int)

In [ ]:
add_t2_conf_unix_dummy.to_csv('/IBu/UK_BB/ML_DATASETS/Brain/t1_t2_tMRI/add_t2_conf_unix_dummy.csv', index=False)
add_t2_conf_unix_dummy.to_csv('/IBu/UK_BB/Cog-Ment/PLS/brain/additional/orig/t2_conf.csv', index=False)
add_t2_conf_unix_dummy

,Discrepancy between T1 brain image and standard-space brain template (linearly-aligned),Scanner longitudinal (Z) brain position,Scanner table position,Intensity scaling for tfMRI,Date of attending assessment centre,Echo Time for tfMRI,Scanner transverse (Y) brain position,"Mean tfMRI head motion, averaged across space and time points",Inverted temporal signal-to-noise ratio in pre-processed tfMRI,Discrepancy between T1 brain image and standard-space brain template (nonlinearly-aligned),...,Scanner lateral (X) brain position,Discrepancy between tfMRI brain image and T1 brain image,eid,Struct.motion,Median absolute head motion from tfMRI,Median relative head motion from tfMRI,UK Biobank assessment centre_11025.0,UK Biobank assessment centre_11026.0,UK Biobank assessment centre_11027.0,UK Biobank assessment centre_11028.0
0,0.695184,26.99980,-1089.0,2.0,1437652800,39.0,62.0,0.238552,0.009410,0.487557,...,0.985166,0.770446,1000046,0.166306,1.252180,0.226963,1,0,0,0
1,0.657209,-37.57850,-1042.0,2.0,1574074800,39.0,61.0,0.150712,0.007369,0.484748,...,-1.590050,0.765128,1000054,0.488937,0.920265,0.132992,1,0,0,0
2,0.598807,-29.35690,-1042.0,2.0,1510657200,42.4,56.0,0.081280,0.007618,0.488218,...,2.003760,0.837238,1000203,0.299027,0.475771,0.074112,1,0,0,0
3,0.638328,-31.16950,-1042.0,2.0,1513422000,42.4,65.0,0.117583,0.008002,0.543879,...,1.693270,0.797509,1000304,0.342515,2.142720,0.111271,1,0,0,0
4,0.635286,-63.02750,-1042.0,2.0,1542106800,42.4,74.0,0.220804,0.011622,0.500386,...,4.094220,0.601949,1000482,0.290192,1.167570,0.165585,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38619,0.649432,-21.24560,-1066.0,2.0,1432987200,39.0,60.0,0.128904,0.007026,0.541331,...,-0.289010,0.688204,6024161,0.230402,0.786487,0.132433,1,0,0,0
38620,0.602124,-32.68790,-1042.0,2.0,1504785600,42.4,68.0,0.136135,0.007845,0.488843,...,5.966570,0.790748,6024193,0.545477,0.832934,0.125729,0,0,1,0
38621,0.604161,-43.83240,-1042.0,2.0,1647514800,39.0,62.0,0.133916,0.008155,0.444603,...,1.042230,0.772951,6024277,0.196698,0.911082,0.106934,1,0,0,0
38622,0.651801,-34.47560,-1042.0,2.0,1424775600,39.0,65.0,0.122945,0.008054,0.501976,...,3.082770,0.851742,6024345,0.448581,1.812310,0.101455,1,0,0,0
38623,0.652501,-7.74656,-1086.0,2.0,1457780400,39.0,62.0,0.180320,0.011226,0.502078,...,-1.359400,0.691086,6024606,0.117782,0.596652,0.132241,1,0,0,0

# T1 Confounds

In [ ]:
t1_conf = pd.read_csv('/IBu/UK_BB/ML_DATASETS/Brain/T1/struct_conf_full_dummy.csv')
t1_conf

,Scanner longitudinal (Z) brain position,Inverted contrast-to-noise ratio in T1,Discrepancy between T1 brain image and standard-space brain template (linearly-aligned),Scanner transverse (Y) brain position,Date of attending assessment centre,Discrepancy between T1 brain image and standard-space brain template (nonlinearly-aligned),Inverted signal-to-noise ratio in T1,Scanner lateral (X) brain position,Scanner table position,Amount of warping applied to non-linearly align T1 brain image to standard-space,Volumetric scaling from T1 head image to standard space,Intensity scaling for T1,eid,Struct. motion,UK Biobank assessment centre_11025.0,UK Biobank assessment centre_11026.0,UK Biobank assessment centre_11027.0,UK Biobank assessment centre_11028.0
0,26.99980,0.039885,0.695184,62.0,1437652800,0.487557,0.017267,0.985166,-1089.0,0.074706,1.25540,6.0,1000046,0.166306,1,0,0,0
1,-37.57850,0.035054,0.657209,61.0,1574074800,0.484748,0.015260,-1.590050,-1042.0,0.069713,1.43688,6.0,1000054,0.488937,1,0,0,0
2,-54.33320,0.038599,0.610478,63.0,1539428400,0.466349,0.015723,0.193689,-1042.0,0.060207,1.34341,6.0,1000164,0.321029,1,0,0,0
3,-29.35690,0.036492,0.598807,56.0,1510657200,0.488218,0.014374,2.003760,-1042.0,0.059152,1.32704,6.0,1000203,0.299027,1,0,0,0
4,-31.16950,0.038442,0.638328,65.0,1513422000,0.543879,0.016232,1.693270,-1042.0,0.081215,1.10518,6.0,1000304,0.342515,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45734,-43.83240,0.031352,0.604161,62.0,1647514800,0.444603,0.013851,1.042230,-1042.0,0.072651,1.51751,6.0,6024277,0.196698,1,0,0,0
45735,-34.47560,0.038755,0.651801,65.0,1424775600,0.501976,0.016418,3.082770,-1042.0,0.068185,1.35167,6.0,6024345,0.448581,1,0,0,0
45736,-35.75140,0.032801,0.663592,56.0,1496750400,0.460220,0.014612,0.716320,-1042.0,0.074119,1.31166,6.0,6024581,0.246757,1,0,0,0
45737,-7.74656,0.040729,0.652501,62.0,1457780400,0.502078,0.017574,-1.359400,-1086.0,0.070715,1.38344,6.0,6024606,0.117782,1,0,0,0
45738,-61.96160,0.033826,0.730108,64.0,1574420400,0.506460,0.015316,0.521898,-1042.0,0.106041,1.22325,6.0,6024614,0.379711,1,0,0,0

Basic

- 25925	Intensity scaling for T1
- 26500	T2-FLAIR used (in addition to T1) to run FreeSurfer
- 25733	Amount of warping applied to non-linearly align T1 brain image to standard-space
- 25731	Discrepancy between T1 brain image and standard-space brain template (linearly-aligned)
- 25732	Discrepancy between T1 brain image and standard-space brain template (nonlinearly-aligned)
- 25735	Inverted contrast-to-noise ratio in T1
- 25734	Inverted signal-to-noise ratio in T1
- 25000	Volumetric scaling from T1 head image to standard space
- 25756	Scanner lateral (X) brain position
- 25757	Scanner transverse (Y) brain position
- 25758	Scanner longitudinal (Z) brain position
- 25759	Scanner table position

### Confounds from other MRI samples

- Head size: 25000
- Site: 54
- Acquisition date: 53
- STRUCT MOTION: 24419
- Discrepancy between T1 brain image and standard-space brain template (linearly-aligned): 25731
- Discrepancy between T1 brain image and standard-space brain template (nonlinearly-aligned): 25732

In [ ]:
df_struct_conf = ukbiobank.utils.utils.loadCsv(ukbio=ukb, fields=['eid',
25925,
26500,
25733,
25731,
25732,
25735,
25734,
25000,
25756,
25757,
25758,
25759,
25000,
54,
53], instance=2)
# 24419 not found

/home/irinabu/anaconda3/envs/ukbiobank_py11/lib/python3.11/site-packages/ukbiobank/utils/utils.py:296: DtypeWarning: Columns (98,99,100) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(ukbio.csv_path, usecols=new_fields)

In [ ]:
struct_conf_names = ukbiobank.utils.utils.fieldIdsToNames(ukbio=ukb, df=df_struct_conf)
struct_conf_names_nona = struct_conf_names.dropna(axis=0)
struct_conf_names_nona.columns = struct_conf_names_nona.columns.str.replace('-2.0', '')
struct_conf_names_nona.to_csv('/IBu/UK_BB/ML_DATASETS/Brain/T1/struct_conf_names_nona_without_struct_motion.csv', index=False)
struct_conf_names_nona

,Scanner longitudinal (Z) brain position,Inverted contrast-to-noise ratio in T1,T2-FLAIR used (in addition to T1) to run FreeSurfer,UK Biobank assessment centre,Discrepancy between T1 brain image and standard-space brain template (linearly-aligned),Scanner transverse (Y) brain position,Date of attending assessment centre,Discrepancy between T1 brain image and standard-space brain template (nonlinearly-aligned),Inverted signal-to-noise ratio in T1,Scanner lateral (X) brain position,Scanner table position,Amount of warping applied to non-linearly align T1 brain image to standard-space,Volumetric scaling from T1 head image to standard space,Intensity scaling for T1,eid
3,26.99980,0.039885,1.0,11025.0,0.695184,62.0,2015-07-24,0.487557,0.017267,0.985166,-1089.0,0.074706,1.25540,6.0,1000046
4,-37.57850,0.035054,1.0,11025.0,0.657209,61.0,2019-11-19,0.484748,0.015260,-1.590050,-1042.0,0.069713,1.43688,6.0,1000054
15,-54.33320,0.038599,1.0,11025.0,0.610478,63.0,2018-10-14,0.466349,0.015723,0.193689,-1042.0,0.060207,1.34341,6.0,1000164
19,-29.35690,0.036492,1.0,11025.0,0.598807,56.0,2017-11-15,0.488218,0.014374,2.003760,-1042.0,0.059152,1.32704,6.0,1000203
29,-31.16950,0.038442,1.0,11025.0,0.638328,65.0,2017-12-17,0.543879,0.016232,1.693270,-1042.0,0.081215,1.10518,6.0,1000304
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
502304,-43.83240,0.031352,1.0,11025.0,0.604161,62.0,2022-03-18,0.444603,0.013851,1.042230,-1042.0,0.072651,1.51751,6.0,6024277
502311,-34.47560,0.038755,1.0,11025.0,0.651801,65.0,2015-02-25,0.501976,0.016418,3.082770,-1042.0,0.068185,1.35167,6.0,6024345
502335,-35.75140,0.032801,1.0,11025.0,0.663592,56.0,2017-06-07,0.460220,0.014612,0.716320,-1042.0,0.074119,1.31166,6.0,6024581
502337,-7.74656,0.040729,1.0,11025.0,0.652501,62.0,2016-03-13,0.502078,0.017574,-1.359400,-1086.0,0.070715,1.38344,6.0,6024606
502338,-61.96160,0.033826,1.0,11025.0,0.730108,64.0,2019-11-23,0.506460,0.015316,0.521898,-1042.0,0.106041,1.22325,6.0,6024614

Add files that are not in the main csv: 24419, STRUCT MOTION

In [ ]:
struct_conf_add = pd.read_csv('/IBu/UK_BB/ukbbdata/ukbb_june23/Oct_2023_resting_conf/ukb673187.csv')
struct_conf_add = struct_conf_add[['eid','24419-2.0']]
struct_conf_add.columns = ['eid','Struct. motion']
struct_conf_add_nona = struct_conf_add.dropna(axis=0)
struct_conf_add_nona

            eid  Struct. motion
3       1000046        0.166306
4       1000054        0.488937
15      1000164        0.321029
19      1000203        0.299027
29      1000304        0.342515
...         ...             ...
502315  6024277        0.196698
502322  6024345        0.448581
502346  6024581        0.246757
502348  6024606        0.117782
502349  6024614        0.379711

[49421 rows x 2 columns]

In [ ]:
struct_conf_names_nona = pd.read_csv('/IBu/UK_BB/ML_DATASETS/Brain/T1/struct_conf_names_nona_without_struct_motion.csv')
struct_conf_add = pd.read_csv('/IBu/UK_BB/ukbbdata/ukbb_june23/Oct_2023_resting_conf/ukb673187.csv', usecols = ['eid','24419-2.0'])

struct_conf_add.columns = ['eid','Struct. motion']
struct_conf_add_nona = struct_conf_add.dropna(axis=0)
struct_conf_full = pd.merge(struct_conf_names_nona, struct_conf_add_nona, on = 'eid')
struct_conf_full
struct_conf_full.to_csv('/IBu/UK_BB/ML_DATASETS/Brain/T1/struct_conf_full.csv', index=False)

# Convert date
import datetime
struct_conf_full_unix = struct_conf_full.copy()
struct_conf_full_unix['Date of attending assessment centre'] = pd.to_datetime(struct_conf_full_unix['Date of attending assessment centre'], format="%Y-%m-%d")  #"%m/%d/%Y")
struct_conf_full_unix['Date of attending assessment centre'] = struct_conf_full_unix['Date of attending assessment centre'].apply(datetime.datetime.timestamp)

# Round values
struct_conf_full_unix['Date of attending assessment centre'] = struct_conf_full_unix['Date of attending assessment centre'].apply(int)
print(struct_conf_full_unix['Date of attending assessment centre'])

# Dummy encode site
struct_conf_full_dummy = struct_conf_full_unix.copy()
struct_conf_full_dummy = pd.get_dummies(struct_conf_full_dummy, columns=['UK Biobank assessment centre'], dtype=int)
struct_conf_full_dummy = struct_conf_full_dummy.drop(columns='T2-FLAIR used (in addition to T1) to run FreeSurfer')
struct_conf_full_dummy.to_csv('/IBu/UK_BB/ML_DATASETS/Brain/T1/struct_conf_full_dummy.csv', index=False)
struct_conf_full_dummy

,Scanner longitudinal (Z) brain position,Inverted contrast-to-noise ratio in T1,Discrepancy between T1 brain image and standard-space brain template (linearly-aligned),Scanner transverse (Y) brain position,Date of attending assessment centre,Discrepancy between T1 brain image and standard-space brain template (nonlinearly-aligned),Inverted signal-to-noise ratio in T1,Scanner lateral (X) brain position,Scanner table position,Amount of warping applied to non-linearly align T1 brain image to standard-space,Volumetric scaling from T1 head image to standard space,Intensity scaling for T1,eid,Struct. motion,UK Biobank assessment centre_11025.0,UK Biobank assessment centre_11026.0,UK Biobank assessment centre_11027.0,UK Biobank assessment centre_11028.0
0,26.99980,0.039885,0.695184,62.0,1437652800,0.487557,0.017267,0.985166,-1089.0,0.074706,1.25540,6.0,1000046,0.166306,1,0,0,0
1,-37.57850,0.035054,0.657209,61.0,1574074800,0.484748,0.015260,-1.590050,-1042.0,0.069713,1.43688,6.0,1000054,0.488937,1,0,0,0
2,-54.33320,0.038599,0.610478,63.0,1539428400,0.466349,0.015723,0.193689,-1042.0,0.060207,1.34341,6.0,1000164,0.321029,1,0,0,0
3,-29.35690,0.036492,0.598807,56.0,1510657200,0.488218,0.014374,2.003760,-1042.0,0.059152,1.32704,6.0,1000203,0.299027,1,0,0,0
4,-31.16950,0.038442,0.638328,65.0,1513422000,0.543879,0.016232,1.693270,-1042.0,0.081215,1.10518,6.0,1000304,0.342515,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45734,-43.83240,0.031352,0.604161,62.0,1647514800,0.444603,0.013851,1.042230,-1042.0,0.072651,1.51751,6.0,6024277,0.196698,1,0,0,0
45735,-34.47560,0.038755,0.651801,65.0,1424775600,0.501976,0.016418,3.082770,-1042.0,0.068185,1.35167,6.0,6024345,0.448581,1,0,0,0
45736,-35.75140,0.032801,0.663592,56.0,1496750400,0.460220,0.014612,0.716320,-1042.0,0.074119,1.31166,6.0,6024581,0.246757,1,0,0,0
45737,-7.74656,0.040729,0.652501,62.0,1457780400,0.502078,0.017574,-1.359400,-1086.0,0.070715,1.38344,6.0,6024606,0.117782,1,0,0,0
45738,-61.96160,0.033826,0.730108,64.0,1574420400,0.506460,0.015316,0.521898,-1042.0,0.106041,1.22325,6.0,6024614,0.379711,1,0,0,0